---
collections:
  - name: community.general
    version: 5.4.0
  - name: community.sops
    version: 1.2.3
  - name: ansible.posix
    version: 1.4.0
  - name: ansible.utils
    version: 2.6.1

roles:
  - src: xanmanning.k3s
    version: v3.2.0
  - name: deploy-functions
    src: https://oss.help/ansible/pub/roles/d/deploy-functions-stable.tar.gz
  - name: lxc-reboot
    src: https://oss.help/ansible/pub/roles/l/2/lxc-reboot-stable.tar.gz
