# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:ob8XAqQ=,iv:h380tZ9AxHi1Cw0mW/lEPES/2ss8q8q1y8CmreWCLis=,tag:EcmwBZPTNVhFN56EO9+o3Q==,type:str]
    admin-password: ENC[AES256_GCM,data:wA1afvZNezthWpcR,iv:55SYB2swLRSGslNsQiw38h0lzeu3S3CkYGzML2/5vgk=,tag:ngQbv/pLIrJHGJD3GqHIyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTENNVHg1YnNMem4xYlRI
            SjVQV2RtWGVwT3VwY1F0TWJ1azBLMGVNVkJVCmZScHNvNGhnZ3RGNXk3RXo0T2NG
            T2RmYnBiei8yZUhtT0ZEWDRaMEl1NlkKLS0tIGJDbWdQNHVEMG41cDRrd2JjK1kz
            YXFzbEJuYS9JVDU4MU9TV1lXMWFlS00KnJZw6LK9VVIZfvsXCfxJOEfuBCjzq0s6
            ARzQIyrHxj5oudqWOYwiMtwRywjnFmMPGiyOM9M7D9UABDmTpURz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T13:05:50Z"
    mac: ENC[AES256_GCM,data:N/CHvlSQ4d7yOX8/cyScDMUPnuLFynB6cNe6k5QEPfDOgCd3iue3nkWd6oxKvS4rhUcIfh0leUMumd58SEAaqMnEo7tl1X0V9oUed6jn7myKO5cQ/6Ds5wNRLnyJXvPIewkVtX2WoRrZuvuNzV31HjdKizYketvho1TLCH8FOFc=,iv:zYg2HsL/kphvtR1djGqD0D5R1ZLpXZjLtPD3xJ4qtds=,tag:d+iQ0l7kPtbgPetIwHiczA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:2JqciDoxCA==,iv:PKSEHPtkoclzpQQE/HGe6f0B0IEtLA5GsGbj65M7jbY=,tag:faZU++FXyu9+ioTN2/ifmA==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:0gjnwbrLulIGF1vl,iv:NFRPnK1tomrErZhGUVdBQJXpeT9XNcvLN02SDZwy58o=,tag:8cF/QaXCQWnufmHsiQ4d2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTENNVHg1YnNMem4xYlRI
            SjVQV2RtWGVwT3VwY1F0TWJ1azBLMGVNVkJVCmZScHNvNGhnZ3RGNXk3RXo0T2NG
            T2RmYnBiei8yZUhtT0ZEWDRaMEl1NlkKLS0tIGJDbWdQNHVEMG41cDRrd2JjK1kz
            YXFzbEJuYS9JVDU4MU9TV1lXMWFlS00KnJZw6LK9VVIZfvsXCfxJOEfuBCjzq0s6
            ARzQIyrHxj5oudqWOYwiMtwRywjnFmMPGiyOM9M7D9UABDmTpURz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T13:05:50Z"
    mac: ENC[AES256_GCM,data:N/CHvlSQ4d7yOX8/cyScDMUPnuLFynB6cNe6k5QEPfDOgCd3iue3nkWd6oxKvS4rhUcIfh0leUMumd58SEAaqMnEo7tl1X0V9oUed6jn7myKO5cQ/6Ds5wNRLnyJXvPIewkVtX2WoRrZuvuNzV31HjdKizYketvho1TLCH8FOFc=,iv:zYg2HsL/kphvtR1djGqD0D5R1ZLpXZjLtPD3xJ4qtds=,tag:d+iQ0l7kPtbgPetIwHiczA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
