# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:ob8XAqQ=,iv:h380tZ9AxHi1Cw0mW/lEPES/2ss8q8q1y8CmreWCLis=,tag:EcmwBZPTNVhFN56EO9+o3Q==,type:str]
    admin-password: ENC[AES256_GCM,data:wA1afvZNezthWpcR,iv:55SYB2swLRSGslNsQiw38h0lzeu3S3CkYGzML2/5vgk=,tag:ngQbv/pLIrJHGJD3GqHIyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTENNVHg1YnNMem4xYlRI
            SjVQV2RtWGVwT3VwY1F0TWJ1azBLMGVNVkJVCmZScHNvNGhnZ3RGNXk3RXo0T2NG
            T2RmYnBiei8yZUhtT0ZEWDRaMEl1NlkKLS0tIGJDbWdQNHVEMG41cDRrd2JjK1kz
            YXFzbEJuYS9JVDU4MU9TV1lXMWFlS00KnJZw6LK9VVIZfvsXCfxJOEfuBCjzq0s6
            ARzQIyrHxj5oudqWOYwiMtwRywjnFmMPGiyOM9M7D9UABDmTpURz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T13:51:03Z"
    mac: ENC[AES256_GCM,data:k06ekjLo7lwrzqouK0i0sNntnBRAczfN506iQdxKY+6IUbRE0iw8BAUXGapb96d4tUPN0dOtAzYoy4p6EOletAZ5pXamPHjuncG7R63VRN+3nXYW9WdKwF993BAJWITUjS9JRT2SeiHC46phmie1wYc2mzqhZT7wSt0MLFXclCM=,iv:1L/tkAgqXTmhU/+3cuW027aYRErKOsEhKVsIRSQxM6Q=,tag:/4sZS+9eBc3v8fpqH/Yh2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:2JqciDoxCA==,iv:PKSEHPtkoclzpQQE/HGe6f0B0IEtLA5GsGbj65M7jbY=,tag:faZU++FXyu9+ioTN2/ifmA==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:0gjnwbrLulIGF1vl,iv:NFRPnK1tomrErZhGUVdBQJXpeT9XNcvLN02SDZwy58o=,tag:8cF/QaXCQWnufmHsiQ4d2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTENNVHg1YnNMem4xYlRI
            SjVQV2RtWGVwT3VwY1F0TWJ1azBLMGVNVkJVCmZScHNvNGhnZ3RGNXk3RXo0T2NG
            T2RmYnBiei8yZUhtT0ZEWDRaMEl1NlkKLS0tIGJDbWdQNHVEMG41cDRrd2JjK1kz
            YXFzbEJuYS9JVDU4MU9TV1lXMWFlS00KnJZw6LK9VVIZfvsXCfxJOEfuBCjzq0s6
            ARzQIyrHxj5oudqWOYwiMtwRywjnFmMPGiyOM9M7D9UABDmTpURz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T13:51:03Z"
    mac: ENC[AES256_GCM,data:k06ekjLo7lwrzqouK0i0sNntnBRAczfN506iQdxKY+6IUbRE0iw8BAUXGapb96d4tUPN0dOtAzYoy4p6EOletAZ5pXamPHjuncG7R63VRN+3nXYW9WdKwF993BAJWITUjS9JRT2SeiHC46phmie1wYc2mzqhZT7wSt0MLFXclCM=,iv:1L/tkAgqXTmhU/+3cuW027aYRErKOsEhKVsIRSQxM6Q=,tag:/4sZS+9eBc3v8fpqH/Yh2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: monitoring
stringData:
    username: ENC[AES256_GCM,data:nfPt6g==,iv:OBRdqF65K19P76ikvH5ig8wS1CdLCsnS7cvlMyJPrQw=,tag:+ryIDLmc+VCrwxiOebhsNg==,type:str]
    password: ENC[AES256_GCM,data:DCieSRczDTsb5Lze,iv:C0/yCoItsjhsJrb57vLggwZN29S6UbyE/fZ/kcpdj7g=,tag:Vpe0Wo5TZ0dOVHTnXtN1Pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTENNVHg1YnNMem4xYlRI
            SjVQV2RtWGVwT3VwY1F0TWJ1azBLMGVNVkJVCmZScHNvNGhnZ3RGNXk3RXo0T2NG
            T2RmYnBiei8yZUhtT0ZEWDRaMEl1NlkKLS0tIGJDbWdQNHVEMG41cDRrd2JjK1kz
            YXFzbEJuYS9JVDU4MU9TV1lXMWFlS00KnJZw6LK9VVIZfvsXCfxJOEfuBCjzq0s6
            ARzQIyrHxj5oudqWOYwiMtwRywjnFmMPGiyOM9M7D9UABDmTpURz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T13:51:03Z"
    mac: ENC[AES256_GCM,data:k06ekjLo7lwrzqouK0i0sNntnBRAczfN506iQdxKY+6IUbRE0iw8BAUXGapb96d4tUPN0dOtAzYoy4p6EOletAZ5pXamPHjuncG7R63VRN+3nXYW9WdKwF993BAJWITUjS9JRT2SeiHC46phmie1wYc2mzqhZT7wSt0MLFXclCM=,iv:1L/tkAgqXTmhU/+3cuW027aYRErKOsEhKVsIRSQxM6Q=,tag:/4sZS+9eBc3v8fpqH/Yh2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
