# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:ob8XAqQ=,iv:h380tZ9AxHi1Cw0mW/lEPES/2ss8q8q1y8CmreWCLis=,tag:EcmwBZPTNVhFN56EO9+o3Q==,type:str]
    admin-password: ENC[AES256_GCM,data:wA1afvZNezthWpcR,iv:55SYB2swLRSGslNsQiw38h0lzeu3S3CkYGzML2/5vgk=,tag:ngQbv/pLIrJHGJD3GqHIyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTENNVHg1YnNMem4xYlRI
            SjVQV2RtWGVwT3VwY1F0TWJ1azBLMGVNVkJVCmZScHNvNGhnZ3RGNXk3RXo0T2NG
            T2RmYnBiei8yZUhtT0ZEWDRaMEl1NlkKLS0tIGJDbWdQNHVEMG41cDRrd2JjK1kz
            YXFzbEJuYS9JVDU4MU9TV1lXMWFlS00KnJZw6LK9VVIZfvsXCfxJOEfuBCjzq0s6
            ARzQIyrHxj5oudqWOYwiMtwRywjnFmMPGiyOM9M7D9UABDmTpURz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T23:15:11Z"
    mac: ENC[AES256_GCM,data:5Ey2WJMkuE/mHHE3qIcKpXou/8e5pydLSqYB1mfXSW7WHDGGTT/hlmIU7iGNoLNt4amgDlfhYUbK9dS34F7+7Jm6Gs5QqDp+4MuvaY/L46PCyouYY4glvTgulu4HLFjm5Plk4oSmTQUkfA0TbSR5GUcLLha2RnFJPlxBluFi048=,iv:DMUKjG80WhP1KpWdsQ5FUkNe6RDgrGq7kRVSX3O/P0Q=,tag:st2WSULB5ZkBhKV6kbSxXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:OwQGEw==,iv:NiQKgryUdcmII4pSVYyv1RyLios8JLj8nqk2vP+DFp4=,tag:RngA4iu4++jvzGNs1sEiVQ==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:0gjnwbrLulIGF1vl,iv:NFRPnK1tomrErZhGUVdBQJXpeT9XNcvLN02SDZwy58o=,tag:8cF/QaXCQWnufmHsiQ4d2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTENNVHg1YnNMem4xYlRI
            SjVQV2RtWGVwT3VwY1F0TWJ1azBLMGVNVkJVCmZScHNvNGhnZ3RGNXk3RXo0T2NG
            T2RmYnBiei8yZUhtT0ZEWDRaMEl1NlkKLS0tIGJDbWdQNHVEMG41cDRrd2JjK1kz
            YXFzbEJuYS9JVDU4MU9TV1lXMWFlS00KnJZw6LK9VVIZfvsXCfxJOEfuBCjzq0s6
            ARzQIyrHxj5oudqWOYwiMtwRywjnFmMPGiyOM9M7D9UABDmTpURz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T23:15:11Z"
    mac: ENC[AES256_GCM,data:5Ey2WJMkuE/mHHE3qIcKpXou/8e5pydLSqYB1mfXSW7WHDGGTT/hlmIU7iGNoLNt4amgDlfhYUbK9dS34F7+7Jm6Gs5QqDp+4MuvaY/L46PCyouYY4glvTgulu4HLFjm5Plk4oSmTQUkfA0TbSR5GUcLLha2RnFJPlxBluFi048=,iv:DMUKjG80WhP1KpWdsQ5FUkNe6RDgrGq7kRVSX3O/P0Q=,tag:st2WSULB5ZkBhKV6kbSxXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
