---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sumologic
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://sumologic.github.io/sumologic-kubernetes-collection
