apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authentication-system
    labels:
        app.kubernetes.io/name: authelia
type: Opaque
stringData:
    authelia_jwt_secret: ENC[AES256_GCM,data:u+QMDZsjyiwrCN6bG/GEYLwmol89VxVzzVfaiZt2rYkDWQk9m8kbr7Ss05CN7HNVYj8T/uHPftxX2iCL1yd7,iv:ocoYVsyn+UFDi4M4Wweg9CgwacjJW2Cm9NQGfM0cfus=,tag:b+D7BZTpiUV9Eu4/g2R34Q==,type:str]
    authelia_duo_api_secret_key: ENC[AES256_GCM,data:bCLiC82CazCDEy21zWQjvfdsUJTJN25X8J3wELUqSyYMMw0s4h/LTw==,iv:wNl6BnQhyBvETRwcNhMvcteiK9MbdVX/TA53XFfArA8=,tag:3yWAlaFNiTUJewQtfqHu3g==,type:str]
    authelia_session_secret: ENC[AES256_GCM,data:Cc2eeiXTur4iI3qyufYni4mIDPduEx+T7ATwWy8hoFG7KcIy7RnJBmZxJeDsI1lkrzaOzRVwkTs45hmg2ZiX,iv:OySk9Gdc53v7/ZcD/Vg/fwkbLedfHK9fSG6Ua2pq1ME=,tag:EnR/jiAYqoA3i84C50SPHw==,type:str]
    authelia_notifier_smtp_password: ENC[AES256_GCM,data:olDZWNTpx5+NvR3nJhC2WA==,iv:jok1G/H3BZ3viCaD1/jvFdDMzTbgoA1f80NA9D4KLh4=,tag:r9z6lXeH9m3Q+YwSNW7n6w==,type:str]
    authelia_session_redis_password: ENC[AES256_GCM,data:8vnXCFAmSVyRSnU=,iv:DwY0cBn5wuy3tJg+z6dw/lj4lSGNe3ggkQ9OovHP9+M=,tag:fL1GkhwwFtiuQUgJRfCSpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zeqkpfz7e3s207ynea0z0auc0mrct0pc7w4sh6j3d0c4qac3dahqj9ufdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTjZma2M1RTRybjUyZlFG
            N2ZFb2gxVm1RUzFZZXpRa2cydEd6VVFPdFJNCk5rbk8yRzJMcDZIZUdFb3Jqcndu
            M1IvaXBEWHlwZkNNbXZKYzFrbURmN1UKLS0tIC82RDZLUm5YMEE5TkZDOEtGN01N
            Q1lKZTQvT2dkQWZtVG91WFVJQVE4TzAKcD86+a2n9Ta/CHPDdvW021SYyoqZv2ow
            rm1gCNXsY694wGx+aktQDn28r+0Au4WhoGpuAJ3jSVvC1jTs/wNTEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-18T07:27:50Z"
    mac: ENC[AES256_GCM,data:nSAuombbKsEWk+FgFa2VJmnAN/XTLvFWbWpaOHpmjHvzGgrpRutwmc4G+BV0DZpMV6nM/QBpi40ibBRztSoTo/8xsewzqAxYyT277h6Et5wd9XpnvpIOcr5EuU/vWFutU1t17ci/z49AYyxpcp2u+hwH1UQx3uyGP7Q6E8sm7lk=,iv:ZM4Ynp/kNyDGY7Rz1KZkf5w+8st/lVx0v4neYL5oS24=,tag:KFtfP61do3dkK+EwKCxH5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
