apiVersion: v1
kind: Service
metadata:
  name: &name authelia
  namespace: authentication-system
  labels: &labels
    app.kubernetes.io/name: *name
spec:
  selector: *labels
  ports:
    - name: &port http
      protocol: TCP
      port: 9091
      targetPort: *port
  type: ClusterIP
