kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: smtp-relay
    namespace: default
stringData:
    SMTP_PASSWORD: ENC[AES256_GCM,data:KR+JRvFuWjbmo/fkeWxkeg==,iv:MtsH9rPV2yRvMCGCebAeogsYDjPNadLGLTHt2I1g4RY=,tag:Kbqbj+Utio65nOnlz+uAwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YmlCU3FMS2xMNEdrWm1I
            aytKcHN0dlZnUnQ1NWdKTlAvMHdjWDNWUXlVCld3RkZqNFgrdVZFUlVhWEVxK1Ro
            dzFLaGNoNFJaZVVWbC9tTFA2S0RCMk0KLS0tIE5FRk1VZGsvUyt5NFBROGdON0Z5
            Vk9ER0lIbVExR1dURzNzL2QrNE9sQjQKRYixvRI11/0DWzrhuE3tYn7JpWFDKvul
            EEwasT/gnmDsai8mY6gKQ9PXZGWVdVn/3l4/3alSGfmyp+uZFGCm+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-07T02:02:18Z"
    mac: ENC[AES256_GCM,data:ZU/a+6ovOOWjuLUXTPtr6mZP1cl+LLyuBGUApTRecX8YOFr6WcQLI/Ex9lMkSIyrefGkiJ4Yr+UzMXhz6IpTXYA31ehxE0xlpAqWaAOfpGYfR3S7LZGDyo1rDcfgHqKaLEKW1il9X4QNO4mEvik9W2N1MnOsc7zmjKXqX2z5xNI=,iv:QefyTiixYs/p3EHd53ZhOFS3R7UDoFZbfplHlOzxD7M=,tag:hVnlxBj6NDuFwPBxrLm8/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
