kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: smtp-relay
    namespace: default
stringData:
    SMTP_PASSWORD: ENC[AES256_GCM,data:X7A+B+mBU2nWF+DpC5TKr5oBrQ==,iv:iIxeX9utNUxCVuY4y2LAn5biLwr63ogmQdqu6ASVcWw=,tag:YG9y2+J2M3p9o0qG++fCTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YmlCU3FMS2xMNEdrWm1I
            aytKcHN0dlZnUnQ1NWdKTlAvMHdjWDNWUXlVCld3RkZqNFgrdVZFUlVhWEVxK1Ro
            dzFLaGNoNFJaZVVWbC9tTFA2S0RCMk0KLS0tIE5FRk1VZGsvUyt5NFBROGdON0Z5
            Vk9ER0lIbVExR1dURzNzL2QrNE9sQjQKRYixvRI11/0DWzrhuE3tYn7JpWFDKvul
            EEwasT/gnmDsai8mY6gKQ9PXZGWVdVn/3l4/3alSGfmyp+uZFGCm+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-05T14:04:08Z"
    mac: ENC[AES256_GCM,data:5CM7jwMBxHaMcFEt8Amjvl+vr1nVlAIEz93rmu4Kt9zof1UMLiiHkeGT/ouHEJaVQtGwQ4Dbuy5hZZ13kyGX5j/UIZKV0rBbZSEOExNVBftflAGGu/b4lYAgGgyHG2T9AGmY8ubUW3MdN8H0Izz0SYzu2CLLBdWoPXrA1N0mtUA=,iv:XWLgImq++M/7+1WaOHl7I9TzZ8lPqGG1VbZHyr9JRTA=,tag:d+SXp4dTqaHXVZBj5WkQAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
