{
	"data": "ENC[AES256_GCM,data:3MFM8bTZqZZ1iHnNakbRpJQiIWu65MmwV0PpNJUk4V0kDuovv+tBzKPjPTHZAQeieBRVgzO5yp5+1ng6i3QR5pfAXDBEnRedPqOmPN/ztMa55NMoFHTaYDmmf9vG1Axbj1NXjFPoUEVzsoOe2fS921HoxDlTV1aEwYj8ixbU9Hv8LY0ganXXgMLAbV/WZgwHWloadq9u2pkG1s0iIjJaEyR8NlRxNEoXzZpiOSyiI0NvyEtz2UhsZBfOdTUVPYFKx0Z/uxL3QzYjEZVKr//9zsoyJ5LhEgo=,iv:OMlNqMMUs/H7hukzViNyLvHzWGUv38MeVQXOUtaFyIM=,tag:4xswrzRvPWg2HJMNe++9iA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y0kzQVNMUERlTmlqbkdk\nZmRyU3dBajNYZ1VLK3FLL3VrVEdDZS9iVng0CnNYd05qeWFGY2lGRjJuMm5HSGxL\ncnFISXNyQTV3U3JHcmRoNndHaGVDNVUKLS0tIDNDendkODFvTk9SWlI2OWVVU0NG\nMkdVZk9hMUdDWE1UK1RteDJJcmhWQW8K9T/zLoFnfLKjnpzF65Lng0q0+9Uk65aH\n4p7W4YUSZn8ZvEDLaOWK65SvgPwPEYesMpP1yeVk8JY1w2C1Brgh1w==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-09-01T15:34:53Z",
		"mac": "ENC[AES256_GCM,data:I5q5Ixs0loUS7iE2b4oED/5j+2EGFqo+VphPkrFiJKmpNFuZuMPSXk+0RXvD3/gUOufzoskkpS2IGRBrFkbbLBF4Bnds8izbVhLVyTa1IFr0j+tG9HEPXFOSPypJbW4MYc9Hq+SB4ClvpvgUjwNmG0SWl7ZiSCv7hCVryOlp3Pk=,iv:oK+Mnte0zPTqAVekK9V3U2WRyMrc3ODDDUDk09xuBDc=,tag:i0DZ1NbjJ6uOVhWZIODXxw==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}