{
	"data": "ENC[AES256_GCM,data:mS/NITW0s5XUk7semILmmMCHuZD5qMUueINPRnGW/FBLcIJW3yvsqZp+9QHfC0FBgCW8Atvlyk1KQDJl+kq3vco+teJ3vAcGRNLbxrv6aqkei3yKXCW0kAs18LxXFC2eFYKgxYqD1yXmAK3ui2YDalBUQAx4zHDOv7h8mJLod17ZK6y0DZBekAdYC/YToHDmOlSaHg6Y29mfI4+3VqACJRxPNz6ASxbZ1wNubinxwStWc7in0VY04X2sumO2dnpn0BjUh8WFBAM6FeWG8zG9pyW/ChLUX/HOUwV/edjxs6tklsOh2u7nvgE5IOZHEAduJeUOpCdzFN23Ds/4+UYvRYnELVgAlqZ3GJ1YJSZUF9ZcCEmXwlVNY3ralw66Hep0dVw3d/q++JiiwZaGImTFmuzmKngZD5T52sYhVr/AFvmVCGZ+BLdDUTN4Y9cOVCc00kwqCdpoEWt56/k0y3uc0EweWdMgebb17DHsX9qGeq9ne4BAvHK0+qqmUF78Gp5N+uanYujtdNIQTWL7n7RATuGzL5YZQ28RUXef1fd7xZeCZkj0cQfeG3IDZrmlPwzQRQRheA3biAtZm2zq4cTavtk2x9eV0JFY0D/z4Tcbk/QPNvELX37HGNQzR9jU+WW86xUPIuliOFhc1c/nuwIOUTvs2cW7GcsAwkIdZcDxEYj77ALEFfp4faTnX5aO0Y/H0L9UxJgVK0NdQskt47MKbYUIMPb+2RcZg17fxf/3j3TtI0zlxXxSHi4Kfd9HlMSlCZOLg9hPNJaIpKndfunL1HfT88jj3pTJtLQJ9ahDQa4jPFRicEOnmk3hTTDyoJfBiQvHQjOGvUHAhUAeEOGFxSZxbl1MDkVXJJ6suougBxbD7cJginHLkjtCItRRy6sWbDkNznZz+QQxvCjT4A==,iv:MIpF5QQM+22GMIpxbK5fT/JsBVGvKGBR+nhdvn8KLE4=,tag:qX3s5uLGVUskUy3et4/0Lw==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlblkwb3BKNXBiNldzMVN3\nMENiQnF1RmVldUY0NFZqMVhOQjkrZTVhVWtjCkNNR3VLdDFEODBTNG83VEhpL2V2\nZkc2ZEcvWVB0T0xmVlNOMERkYXA3eGcKLS0tIDRIdzNkZnY4QlBmQ3dLSUc4MktS\nSlJGRG1kTzc3VE1USkpHZDBQd2J5dk0K0EaNPGpzG4wqmG7yYOb/TqS3lFvb0xsq\nPbvq1rVuJW1yrGUJk73DQ4laYjmKcwBFqDfYFKHW8h4otnOgK3zK0A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-09-07T13:04:14Z",
		"mac": "ENC[AES256_GCM,data:9/tBUHbWMnE4tmMXwUtBRj5IVRUCpR/8Utl3avkVN2UC/X2gzEhoraLJ/WBKb143GZ0S5puxsfKZ8YtYLLHsUu5k0BpLLkR0PBeRVIybxnBNETr0Z5b3ZPmTb/3935JbwVo2Ldo/yoH5QYqGAy+r8MfiCqGco079Cckps9fTECk=,iv:GvbFAP8GzRdMuVU4D7JQpLZpzui1fkH9P1tQCYrp69E=,tag:qsTEWoKqlvS6h9l9PePU1w==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}