{
	"data": "ENC[AES256_GCM,data:keShcataaWJYv7EbN8+oAVt+AbpT35mullzIXRhtZiKEkuAnoCni+6YHDcP3DZeVLR/z80DYtqnfGClwu305taLataR46me3ju6QvpHv1G3xQ+zVznKarhhe5sL37no2rqkwSBrUXCIgaI2k0yQ5hmfb4STJfryUsMFI3cekpxH4Hzv6HRjy/Cet0f3mk94KmbnYmq2AX2V3KuAB7VqxSHH/fR1SuflbaOnWDdUS199SFX3HcAmTISzKMztc41249BNiOdCJmOwMh8oA285r/VfjtHIrNzYz/OxMvisRREUCPQvE0vhrQhqb7Rc6/3OGTrPMXtqG2dvyDHbNCD55Atj59n/d6xbL5yqzTnoYuCnaYRRbKp8WGMnctEoTlLGo+uKhxsvgYWr5VaoIG+cc0SCmC94IC0iXloAyGPFdjju0lzu4uyRPdA2me1vgj4dPKYnkFEpz+yGp22dQNGWd3TFCGiTSbDnkd5DxL8XlLLgVVrcSv3tq+WiQAuv04Lbnmkch6Qe6iffHm2LjgyxdPFXiCQcr3hqDF3OjPr/mi6GqgZ9ZlF9Db6vNiq5H0voSYQ==,iv:MWnndH3F1LLRZJWI4kf30LR3T7NAwquuvLCpwT576qY=,tag:V0pjFtoxnCZ6gmn9acE0Kg==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlblkwb3BKNXBiNldzMVN3\nMENiQnF1RmVldUY0NFZqMVhOQjkrZTVhVWtjCkNNR3VLdDFEODBTNG83VEhpL2V2\nZkc2ZEcvWVB0T0xmVlNOMERkYXA3eGcKLS0tIDRIdzNkZnY4QlBmQ3dLSUc4MktS\nSlJGRG1kTzc3VE1USkpHZDBQd2J5dk0K0EaNPGpzG4wqmG7yYOb/TqS3lFvb0xsq\nPbvq1rVuJW1yrGUJk73DQ4laYjmKcwBFqDfYFKHW8h4otnOgK3zK0A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-09-01T15:37:44Z",
		"mac": "ENC[AES256_GCM,data:F1H7KOpqMEcx/0yx+lGcFtlYGoy8Hcz3Jpk8Mjj/IzTkOfYm4XEoY/V08huChkhefENVEfCWqrYreDuRbJZjKZn130w6Vgi9uLC7ucL0CJ/cOsK6dqM4wnpbtasCKmRF/OyzubiwNuKcnf3pco4harqwOt0vGwXpykEpzknqo4U=,iv:Onjga9sZfxPZiYNjEyG7F+D196dvHe2FJgKpELlLQOs=,tag:Q0h3yvHpcXe0QKQrCvbQLg==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}