{
	"data": "ENC[AES256_GCM,data:cGft6vFlWO9WaWCGBhqa2vaIG+xctF2MnSLEBFYFV2Geg8ewIy7etOfuFJArZcbxpWynSBtg0O7yEBluRvJIQJUSuGef/vamY+9dIs/YxsSZsEzBnBZhl35uEgCbuWzfbipxOEJ+2mYYXXYAhxDfa3eaotiH63lzS3hCW/NquRFbhrIW78BfpTiF2fMXhz21ci2W+XKMTcHn34fwkMS6NyXj1vW3qQiG636m9/45+devUzV+7HsFMI8d3WO1tgEzOFHHfqtCDAzGrzzwiTScr2ZCBmE2FUdSTCjD6rxsvCXvU2+puVz8VK0C7VZnOgvpoDHVI/ACbE0yf325lcyZusE1cThkE9sSpqTAxUf5yKihd3RYffhqmw47DR7jw4eLtO4uYEV2OWW6aiz6c7wKEftcxxYtwOcLZ9JcLbQlwWHK2fTV3pXfeOICf8sra3foucNYW1hjwTHJAREHliIUi/xskOJDKIn7UhwmiUKKSYnvTpkWDhrJrls0zXY6x0Q7B27wxi/0bHpUxqG5f2K7WastnkQvDNuO+699bP6FP3LSQ9KF3fz4QLlQxilGwS429KIdRUCWt87KdtzJoR4NGO1NpUQQVYtTUVDroLoOYXT6o/Q86wSQZ52g8sC6Xd6TyE92USyMGRbHAEWnzxSEFspHpA83vTYxLVrnO7cGxVK/QjXLjTr6uBdZsjf7YQvcYWUeujEZ23JEtNNXtUmEq/E8ka/4WcUI,iv:J+y5BBd1VJ7Qzlc7WVM6iz6ehXnc/kWRkRkcf5TZsHc=,tag:yzGq6m22AV7f8jLDcS7RwQ==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlblkwb3BKNXBiNldzMVN3\nMENiQnF1RmVldUY0NFZqMVhOQjkrZTVhVWtjCkNNR3VLdDFEODBTNG83VEhpL2V2\nZkc2ZEcvWVB0T0xmVlNOMERkYXA3eGcKLS0tIDRIdzNkZnY4QlBmQ3dLSUc4MktS\nSlJGRG1kTzc3VE1USkpHZDBQd2J5dk0K0EaNPGpzG4wqmG7yYOb/TqS3lFvb0xsq\nPbvq1rVuJW1yrGUJk73DQ4laYjmKcwBFqDfYFKHW8h4otnOgK3zK0A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-09-01T15:43:48Z",
		"mac": "ENC[AES256_GCM,data:3OL/cZMeDSZoc7W98BS8yoUmzVi/WNY79sOF9BlzCm/EKHBwYW/7t3PAeakJZ8jUj5IgiijAQ7xtYvIOhXxWK1CeDNFFUwhGNo/mmS3p+7b2ww3aFCTf5duwzrvewOHyRbvhnwOiR1GvgMXN8c2VfKBJZS8op8Z+AvGQKuBouPk=,iv:4aWs7qipo0AX1nIdgxMveZ8TTRSW9LTHT41Zw4/s0pA=,tag:gsXj+N6zmaxRefdkstpLDw==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}