{
	"data": "ENC[AES256_GCM,data:fkzax8RGbhAhZRTX9YBjqphUoJ19KIRjTkuI3TmTffOZRD9FCcXzTpEoyGP7NxmgEqQmvjzOzs92MofAw30T330EVGSx0sTuUezET/US6GOA3gqaez0YZHcPHRc8vPRh9HEkCyHQIWx9ZOsYzweGGDJg5HVqy/cDClkBbsM2Sq923ROCmzGk3VQOdWkYO2IJrp37uD48XmEVgp3C3TpFh7u42vg7Hi3JgPu47QaGmMExpYF3BeR1M/hCIyYM/N7TFBPyN6ngR/m9Cch+cJa+g9rSOhBa1rZyv0uQEV/fqSm12rQALOqkZN2A6Fm9gh425XfO2RUf7nOfulnLVO35zASewEpfVCoL4G1uZe2EMv/abE79WeOeeHQeQfyZ+p7SCg6BjGAVAAY9xVUK0QxQfALIQm6iIcrazBk7OdzhgXrwHJp+Z3b1Z2PGREBC6StVJznkbovuMncbvorzIlIUQq/bGpCPO7FOaLcC+ct8ZIa1ub3IciKK8NWlacNhDLZpcDA6+KvMJ3PlFPB2kOxXVQMQVs2YlM3/5DCk0w4w+1BiMvOdqpvAO3xNOqMs8t7vdxRUR5liBwpmn35D5i6ke2wa2CbdRrulUs7Nst+MMYasEzNlrGzXt2VzLnFK5cGfId/p/PI+nviBQE6/2kAIsyOvMjgbrlUvENIeynmhCiGVhLZf/rhNejCI+aZlvB5edMyf9CN0SD2AUOSEW3X/ivNNmTtfsXo+CYHQUjc4at3+LE0hjBizmlWarvf2vh3coyi/d79hDoMuhejo9jtEod+WyjJR4pVi0hHnSN5FbdZU+CIf0Dm9jtSqPAPdSIrWYN25sEAiTKGRIuBI8bPPaUBCJ13yMPckiF4GarBn+3aG7hyqhvFMA7MhKgHGAbQXz+Jyt8tx7VPJ8ZcuDw==,iv:cO8t5ojCSPrymldMiA2ktDIAb9XlV5jAKhBXw+NwBks=,tag:RWjHLtR7/Z5TSIm5F6PKoQ==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlblkwb3BKNXBiNldzMVN3\nMENiQnF1RmVldUY0NFZqMVhOQjkrZTVhVWtjCkNNR3VLdDFEODBTNG83VEhpL2V2\nZkc2ZEcvWVB0T0xmVlNOMERkYXA3eGcKLS0tIDRIdzNkZnY4QlBmQ3dLSUc4MktS\nSlJGRG1kTzc3VE1USkpHZDBQd2J5dk0K0EaNPGpzG4wqmG7yYOb/TqS3lFvb0xsq\nPbvq1rVuJW1yrGUJk73DQ4laYjmKcwBFqDfYFKHW8h4otnOgK3zK0A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-09-06T21:47:18Z",
		"mac": "ENC[AES256_GCM,data:XTVkldFakSG36Yks4BdQPOzJ6xH0h8GsnsS8onYqBcjpdURX/Gp53MSKRkULkZNAUrzAGjAFE8QlJhc8sRfJPVeypTJB7OXKabaw7iSExWi/Zuer6ACIC647v3Fmn2cuNjNjn0USSonPf1wFWJkyX7O1w3S/C7eKK8w+OCyTiko=,iv:RjtS28POob21sL4x6zhj8VAvmpVbtACr0ffl5MlCCPc=,tag:BBCbJgji7R3b+q9i17wvsQ==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}