{
	"data": "ENC[AES256_GCM,data:pvdIWfWEa46je/39b5oow0nKrsrc7NvUB1S5/M2xnRUm5lgK+5wXAZQQ1+I2HD7t/wLPfRGqqHEAPGr8gwI0wHH65ONbhB15gsyJw9FhEtbSLclJrOWZnR4oc8IliJsbg4L6I6wpNorzlztty/fssrDSJ0VLHQm15gvdiV0gX2iX8OxWcRgoGFV1RxYjfEU6XTK2R8/AONTKwb3MqvPbJXBDH/tVHszW3nRnZfBKdXIDp/F/9JhbUyxSriVlTctoDD37UyPDUbdZWyWLvva2DK7CScI0Icvr+ZoPz2zAQlnWJpWjRHCjm58txPcGEw/ec+vQyIFmBO4oATDTDDHAsPaYJogqWukyxPfuLGVKUQK4UeFnIZ7c6EZKJECr+YUidn0zGv1hYq36ezdm0Seery8p+4ktFxbORkBHqudKrB8VJhJ3M8syY2mz+gLMbjULWtL3xT946WwdunOBn9zZh6vUAdHwFKpMqhugZEsvSboqY22fiSC6B38V09qabIzm9XTSd2VuplvwSLNma+tPcOw/dck5zflNOg7gTAiSyfnt17Fu3l8wvqW2wumug7fThovL4BXkTndsRJI7HjsCxtx8PeWEcySFATQo6vuTswjym+1DsGns9zYJ0j/Xkwh9VaquVh9MGc3VeZI9Yzy9vA77eAaf4nkAHW2D+OiD2TljrakAHWOI2B0xBUZWh8V0+EHdLnMaOMC3GdfwrjsGWvxlRdq70CDVSIFSJScmF+iXnNxcJmo8Rl4nvekkNZPaZOyNq8uDMzxqAGKzhowd9GqEdTdpcO4NmPW19oqMTzTtnzR55fK5Df31NaR3O2ELwUv02uHmWsaR3XZgVhSZGOiQyTAi9B7R80MY,iv:4ygkqSgzg1rSWnIIA5JEPmXb7WtA4pzcsKRu7ura3z0=,tag:etalMNTaZxxigtmRqUWSYw==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlblkwb3BKNXBiNldzMVN3\nMENiQnF1RmVldUY0NFZqMVhOQjkrZTVhVWtjCkNNR3VLdDFEODBTNG83VEhpL2V2\nZkc2ZEcvWVB0T0xmVlNOMERkYXA3eGcKLS0tIDRIdzNkZnY4QlBmQ3dLSUc4MktS\nSlJGRG1kTzc3VE1USkpHZDBQd2J5dk0K0EaNPGpzG4wqmG7yYOb/TqS3lFvb0xsq\nPbvq1rVuJW1yrGUJk73DQ4laYjmKcwBFqDfYFKHW8h4otnOgK3zK0A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-09-05T14:37:11Z",
		"mac": "ENC[AES256_GCM,data:KdIEMWDz7WgtBP8QEPLs77WiCy0Vam8qFPq9KVIGNgEYxuqmvicTgYUupOqhxIqjlvRiF3aRNj7B2yPNX1z8AQPHBg6PnOmWc/3gaot92pOGQoxrPFGu44ZbZHGkMIQmo2zYVZwI6Tlxpi2rO+yTb8SRhFtYtVfCafcAJDHcYuY=,iv:866thz7KiAX650iyEitACZE9Rqzg0OFvU9jSl3NQOOk=,tag:dXf4i0GF1YUjxziLw4xpRA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}