{
	"data": "ENC[AES256_GCM,data:OQi2gp/T3dXMvsR9PSqFUwNOkSK2ezLWt5R/8yb3J6wMWEBUiYPB/yhMR/iqVQfhCR9BfSK0cnFxFchh+/gnJfxYuzRxF4dCB+CWr8ZXP3qhZTSfCMF0hpQEEf0Yxnr5dnzTixdhfdgvZJuIoSIRtQktjUpp4iazLvHSMOub889j5Mm+WIvc2R9/b/i7NF4Thu3zTjphlXKEmqDbJqIu+JhaawCxGV2kZ6cqX1muOJItuqHclX4lseuS/W5NHNrRkIhZmEQhpkVPTtd9NFt335fBpSo8YS1lp5Dy+E058R+iw9pEi3LDItFiPdCrpzi93qhkKf1Y2nWbkP2IyXy2x5Prbzx9hu6bn2PQr9mLLlJy1/EuKp8N3otzjqLMXXtbqzQXDx+hmar5lV13cLerplGDAWCZskbgp9OCB2kc1arPxhWTC8ecDNAnMjAks3QUQR1rWQLIvCg3qWXIntyigdcq9VCrPMJYPq9Z6Sor7ASPzfGh7hoLELs8QOwjkOvviL76dkLz/EHbczwhBKVlEuOr1U6P+EF3yzNmfPqh13cvO5CraqMriL0hIH5jzHji8QsGN8sKIv+awP13ydC2R9o4ZsaSeSxcVyppoiSBAJd3AdUFHHdRsgrNZembGk+NS+eRGa+YXYG869PcNOWu4cZq9oRnO129KUI95KEliDLX8SffduGSnYesluaz4XKGCPhWO9w1fs9Pwn3EAgHuIUcVj6fuRSvoyeXJVWh+ksuifxA3M3tEEojpjKyi2xVW1hap8d9+Hzqn3XN7Z7jdVmmPLON1LpUhxQH/Y5a2d9IxTcclPNv6NFh6Oc2OxmtONfZQD9op0jC9ZJWh9Pj+eRbe/OaXwKViX6s=,iv:1XS0/pxTDqRI6CGrwS9ezWtBuaDwlstbwT2GFMhc6U0=,tag:uGSFwWDqA+s/Zw8iNonkew==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlblkwb3BKNXBiNldzMVN3\nMENiQnF1RmVldUY0NFZqMVhOQjkrZTVhVWtjCkNNR3VLdDFEODBTNG83VEhpL2V2\nZkc2ZEcvWVB0T0xmVlNOMERkYXA3eGcKLS0tIDRIdzNkZnY4QlBmQ3dLSUc4MktS\nSlJGRG1kTzc3VE1USkpHZDBQd2J5dk0K0EaNPGpzG4wqmG7yYOb/TqS3lFvb0xsq\nPbvq1rVuJW1yrGUJk73DQ4laYjmKcwBFqDfYFKHW8h4otnOgK3zK0A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-09-05T13:29:27Z",
		"mac": "ENC[AES256_GCM,data:+kiVEzOclQY2erzufkdKTol2BTYGdwgwMxRMlbOJvuPtZq4gkE9bPd7sZ74ikNClzSdXmGZ2Z+JaInRo2CQDPVNQU81xdWDr01qqhTP3YuuAce+daSYCxi+Hdsim0fCvtUYIDd8QohnPH6C9JO0rCxX6drpE9tXblR+AFbXE+j0=,iv:CMLr5bREDaDLkFrIywFtB96FJ/znZuo0395P2HMUhlk=,tag:evb8EhYAnDnuQJ4C7l1aPA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}