{
	"data": "ENC[AES256_GCM,data:yOFSaiYJvSGW87RT4Zrwmqg4sGShN2r4EKpV6mCsKGaLRbZjS1uYVYwVz5mJ7QtO4qCAXhtSGQ9A/rwIqeZWMXdQfi0RrjMInaqZ3wKIhWJNE7eu0bsI7qaAGuvHZiSphHvueAa23aONYFhyMJlhsFzBrFAiTVChMutARaTMMyDWScsuvBNgRn76/cl4qGdhM7inFBdFp2hAvJIlryriXODHavPdyNEVRbXQXWdwFITFlmg3Q4adIpqcdiwY5Jfu1gu5NJCIRVsDShTbLqqmxR0XLtUatanI3XHG9gOseXEZMihmxZY9dlndulamp5mqUt9mRud51HBUFqHH8KjniI1MowzI/nUt7IytCNH1kXY/1CbMyCF8bmAPjbXmKj9ZztmU0e7NV9R3mlZz7LZiczSwG7ppNCZrDkpI0t1b2W7R+8sMoK78Jv6R4VJwwUj9io3iSVJPux0jMJ7rWOq8XMSUOexcP0NOQbUlwv88iwRlr8qk3oewxS69tctrjmylRD41l8KfFY8Y6UGi1rT/E1dVnqjynx8+rVU/48xLrqXJE+IguEHM3yT002eqZLh2K3d/uOm0jBp10uNK8e2m7nDfFkw82Kww38sThiTgG+nMbEQ9GCiEazcN9WHMgKLUbdACQbrUzu5Efomx5TzbbtNVg0PkZSjgL2n8MYPIHdwRIMMqNq2i4OFj2x3Eg5ZWva13OJBSgMa8G1gO1ymY/gaqF9QYU/4L/y9XZufXLW9hiuAa1qsCA5fPRoGBV9GeyuM2pXz7brBetIe1p0ILYKJIh3T4KWwp0nrmSwOlwkUCusdV02dy7GmTO8+4H8kFz+Kl9y6DW9JVGuCACkGEc57Cdmy8JQiD8wVmUkVFatM+9Oo=,iv:/FB8hcRFPSgECHkri0VNcdoPYLseSh4mURw+WphExHw=,tag:/xJby77E7N8PEDZyHUL5jA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlblkwb3BKNXBiNldzMVN3\nMENiQnF1RmVldUY0NFZqMVhOQjkrZTVhVWtjCkNNR3VLdDFEODBTNG83VEhpL2V2\nZkc2ZEcvWVB0T0xmVlNOMERkYXA3eGcKLS0tIDRIdzNkZnY4QlBmQ3dLSUc4MktS\nSlJGRG1kTzc3VE1USkpHZDBQd2J5dk0K0EaNPGpzG4wqmG7yYOb/TqS3lFvb0xsq\nPbvq1rVuJW1yrGUJk73DQ4laYjmKcwBFqDfYFKHW8h4otnOgK3zK0A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-09-05T15:16:27Z",
		"mac": "ENC[AES256_GCM,data:vJVQnhW05bj0CbOCEYcSwfrO/+DNtX8gXBEfLMRvc9YzqcmCeFUEXxHBNxye2VtsxOEJN7lPDZ8KeADZdS9Wstpl7agCzCrYffNsKO62G+RQIYvR20zIYSmIFvqcvQDIaOy5Cce3PskZ43go0NSmkpdmN4S7oSyBag7iqGk0ICY=,iv:g9XsBbx2drF+reLbx+4/sTSdMCHNh4+Y5HZrODaHO8w=,tag:rF7uXB3fZhFX/e5sNaeISg==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}