# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:F2e4jHJEdz2TwStyx6NHbglV3Q==,iv:ok1jQ6Kn4fkCeBBGLfoQ9dd6uXSHofunvq1xGhjGmKA=,tag:ULI2rI4jc6FmtgwpCTyvCA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:7XOB3nm2HGAdsKShl/mJf37m2uZZXwuz6q4Gx5sz+EGiBJu7tA==,iv:QqJAa7tZ6LQw+WOKfj8PIWP7rkUHb9ZhRTAnwN9uvFo=,tag:hGWkur3H7RrgnwVo78rYug==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:1YX4TGX42rtByJWhF1Mf1v0=,iv:xbQuvkUzVqEAQfQYAVnKbI3+tO3sSUhBP0W5Tyc5nAQ=,tag:6yYxQYEMLBli6PyAzmtDVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSktCdnhaZkhZUkROU0ow
            b1lpNUNXZUt4TldkckNjWHhHeE5uVzhsV3dVClgvZTRJaG9ZOWF6czUyRjF2ZFAw
            VFNTQUEyNTdvYm91SzJaWDRnamtURmcKLS0tIHgvMzJFelg0SWhzRlRUa1M2dGdL
            TWk5MEtGY25Ea1Awb3I3UDEzZ1k4TjAK28NPTLXaUibU6MX6NFate5TtCogItdbO
            biN53v5bgEXp4AwFhO70sYUjUAAu19yVdtVeF4r/G1y6mKFUf9NzLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-15T13:56:55Z"
    mac: ENC[AES256_GCM,data:h1CZVrirG9G6Q8jjBbsiP/N8sbtJakHSMBXscFwvzH5/nAJC+nZQY8lA8BtRorRqG/bHvNnwC++PvCiYzBZLNr9B3iWiI27uPTMxL6SuSXLkHfcts4wJVAmtGUh02BB4PQdBvd/Z3zZ/mOdbJmqPhJeVWdC5aRRBE8Q+tdzLsTo=,iv:ZFqjarzdsPP98S2VdGXM6MN4gpBfRlVUWmeez6t0fkQ=,tag:Hgp2GE+ORtA86L+I9wrmtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
