# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2dTuIGXFZuXDNbbFjVJ6xtQNaw==,iv:zN4UKqPz+5wKH93g6LHEYZoxN2xTUsOFDPfKkWKNLY0=,tag:AuVpJBVLoeeGTaGW1+Q6hg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:I+0wq1SIhf/xeMNJXz8me4KYw8XFrHYnS4K0BxC8VOa5M/sxBg==,iv:nVC5VRnKrZ/Y302PgQfg+FQH8VF4+mxgbEJJFbtwePM=,tag:saUSSg1aFC00YulEVUxsOg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:LPIEr8P6nTwK9EWb/rWPiRs=,iv:HrLUHoeNIA6Z1f12vXwTKjEx4GDb2pktvPn05uxST24=,tag:pmXI4sQLJ+Tqk+cJDijPpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzc1Y0bXNvellNT1NteTRr
            Y1ZvWm5JWFZRaU15RVpqc0FlUXl4N2t4SWdvCm1IbVo4Wm9PRFJrb2N6TEpYME9w
            MVBFMmZwVXorcWZSVWd1K2dzeXIxRW8KLS0tIHRMM1ZMZXdCNW5uRndFdUVaT0RZ
            MXE1YnBON0F5bmJyTUdGaC9zbkFSS1kKsOk2TZNspLUk1AiRFcg5/qam5dHpFuEG
            nzMAaBrzDUtcQo16rzdlDFj7dxvKLdoqJROCE68YyCJPZssrNNZHOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-05T21:47:15Z"
    mac: ENC[AES256_GCM,data:1flLVzdg0lRkgvt3cQ0uy3ld5LraQSie51L6gx11ExgSZE2IXpScgQ+1+ZTQkonX2uCZDGBBzFwjSx3A35IQzSR3kY/XUc4ZtO3Wy9SGTaPCMZCg1gAuEau1izvjX5BD16nsVGOADDBiC/zzn+g/YDQQY1BDLccGpmSjc9f7vSY=,iv:rbV/jMw2pEPRbpvis1d9VYsETSbgVyDFJS3p54fNuXg=,tag:Gi5grnR6ucDykDHndz571w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
