# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:DyM8DH206aMmsnt9DezWkGZWIw==,iv:YRaz9w74/cM0rlA/I5bLvRFYyr4Bu0r8xugXxp36QpE=,tag:KJpb4aUaVHeVjuRJQJgtSA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:zL6h7M1NHo5PMr4Zgtar646ByhQjJzjb688O9OS7GzpcJj/NoA==,iv:D8+Qk/GOQv2XB/eyCJiUX8me3YXpMMsOPcsOjPURlkI=,tag:B8BrNgVW6iL7OQiRG4NKHw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:U3HS1N3+t/PoyJpL9Fs4Aw0=,iv:I6NNyGFza4NBog/DdIYE/Yf+9jp1QQB01oLU8FdYtE4=,tag:67WW3au04gk33KSEr+nFMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeElzdmpJaWFJMUgvd0V3
            TnA0K0k2ckdUb2RVUHhJMjdHY2tkVlgzeDJnCnlRZ2VrcCtNbllSLzQ4TTNEWDR2
            UTBsZy9TMUYrTFZpMlNqN2JJWXFiS1kKLS0tIDNSaDZhRTJCUEtDRDlWQUl4aXlO
            alNPVmFCbWdiTU5iUU8wWTB0YVB5UFUKb/cQMmv92j3o57Zw8xr38IMzELtLWsNV
            Fl3tLnBt43W44BzBv7QRhLbrgHvcSihh0Bv6xJ5YL5SW38JXJlVpKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-07T03:20:15Z"
    mac: ENC[AES256_GCM,data:0HtsgAKsPBbYaCSFQBDb1QGWERMF1dxMAvfMr6wW7jeg9xpnrg5f4U9yqoAKC1hylwTTGHPX/RlHtQ/XRyCXofCSsuU8G1RTAOoFR35pQIOkFN113Kyq17uGpPsb6ZsUrpqxvMNgUPYhrynnIpIDRbtgz0PVBDNlBD5gPX5kwq8=,iv:/1wyyca0y8Wl42XbOcG8rLSqSJo2J2/VcYP07OafzBA=,tag:/MljqWaFAuTQ7md8Fvru/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
