# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2e90zNbk1mY31KfVUrwieKY24w==,iv:yfDT4IGb9yew46Hlsms97Ps/gt8/aDeTOvEARBPKvwk=,tag:3t+/9TZ/61o4EE6e5bbVng==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:LceCeZJKDYyIbtTZzmKD1PLcp4oZZtRQpPbNYK1+v8UFqgIR3A==,iv:yA3UetV4ATWzosUoQVlXG9e4h2jQdKG6VNyal+vjGek=,tag:DzfBPAnpsftd5trI9l0avw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:3j1TMsZdwnN5QGnYMpcVUTY=,iv:Auv0IV38g21iAGYiM3U68WA4fK5ou6v8ipR+nrn4MkI=,tag:r1RTPnG5VCbVfQG4P0O+7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZzE5TnR0dGpxRHdRSGU3
            YlNOYUpOdll4N2Y1akJXUUdYWG5maWhwVDJzCk12ejJtcWJLSGliVDlsNTdYL0R3
            bGxSS3pwM095b2hmNk1EODArTkZqSkUKLS0tIGZnT1NWSVNuRkdSZ3dUeTkyYWJm
            VXZSV0ZtWjdSZW05MjJYQTMweWd5Q2cKi6EnkiF2DnclVcR4Zu8fSqCJmA8otktS
            qRzFC2smduQMfFf4DMv2cNgQdwqqHD8Dt/VqoD5KxQSsoTB72qCpuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-04T21:50:26Z"
    mac: ENC[AES256_GCM,data:ZttLQLC8Lh+M5YJJ13tnqrBBzMw9Z9TE63TOonuKjF8H2NGr8lCNKqBE6nk0ces1P9nFg4OA9/E9b13mCczJiKSPvnfIX7jlBTd5FDjODcCmfXDH8YC3glcJhUVa7UkWZlnxfkbc2lLIPALOzlJemPdl1IFLmjezbiLKnlc/S8U=,iv:lnzn/biBhI/YZVQt7QxfNruuk7lSKNGkLOgU9oplnbk=,tag:RV59t3WJUh63MU1pHzObUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
