# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:RFFhgkhOW7+cxbI1VyfzP+lNmQ==,iv:+4p8qvzKufkPlm9dn3pxakYcdwj2ah0CXitMTjTJt78=,tag:p68WtoPCb4yjmTl3dX5zwg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:pDydOBgerUE/E+QL4tVNBKlBuJMuYFpLflFLI1UR+DQIyCEx5w==,iv:AgiTjMYE4jvFP7Lkvwfjx5Szc+7kzm2bwe1WkwhOZPo=,tag:Tb9VzWUezPKwOiqEA8NbQA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:tVlj2tmDWQldbQ4xCaUlJQM=,iv:/fBP111lZwGP6VA7TtZUaya+OdZzrVUq9vpZvgDtU78=,tag:mByh8gXMX/t1WLVppxWX2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdlNjOCsydlFoVi9xMkwr
            b09aS0hmRnFjL3BjMjk2Szc3R3UzdzRFdnhZCkF4QVVnbTZ4dWZZMm93NTRTT0g4
            UHpEamEwQVAzenMxejhQWG9nT0crTjgKLS0tIDBGc2hqYUtheTdGblpEMGNnY0I2
            OGQzREtoLzJvUlZGRVdZSm5pZWpmM3MKL922p8eSkAkqGyJa9tqV4Gh8s42Iy+ey
            Zc3jm/jLtaVJ3XoOY1OSTPOnCBxT9ko2fAd3WcmH2Fgsi9ROIhzRbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-14T14:32:59Z"
    mac: ENC[AES256_GCM,data:ij+dFhsbzPQg9bdEjk9KiMUsvdRoslRvsDEm5oS7y0ax77zvQnPesDY/Y/TeeSs0F5CuazDT5B4MflM5WYMialVWMC/AO9ie4rUxnGVzeSWQ+LH4WVeV+np2UosFzxMR1L/qmyAEh1eNv56YGVzQidwiAGBaMTZ/Jl2ixIOgJD0=,iv:N0v0ibjR5/Du9WnRmFQiZ3h8MJ0cn5SW2aCA18nf3aU=,tag:f/d8HNgx4Oxq/yZ9hlfsug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
