---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  #- blackbox-exporter
  #- generic-rules
  - goldilocks
  - grafana
  #- kube-prometheus-stack
  - loki
  #- pushgateway
  #- smartctl-exporter
  #- snmp-exporter
  #- speedtest-exporter
  #- sumologic
  - thanos
  #- uptimerobot-heartbeat
  #- vector
  - vpa
