---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  #- blackbox-exporter
  #- cloudflare-exporter
  #- generic-rules
  #- goldilocks
  #- grafana
  #- intel-gpu-exporter
  #- kube-prometheus-stack
  #- loki
  #- pushgateway
  #- snmp-exporter
  #- thanos
  #- unifi-poller
  #- uptimerobot-heartbeat
  #- vector
  #- vpa
  #- sumologic
