# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: kopia-sync
    namespace: default
type: Opaque
stringData:
    repository.config: ENC[AES256_GCM,data:B9zDKZ7eolShD4TGbAkY9/IsewbnERrHogMcI0sHx4COsOOhOxBVtKFY6Cbt5jtPP5N9F8qgR1RyAYOWs2XWz8DMcWO3OYw4E+gInfz2AqOif6rBzitrDyFTCCxvJFnFOoKECVJz0iGRZGweco8VAccbsUUU2mRK45tntiv17zleB9dd6oMDVCoO8tHzXgDJVlnPj8Svc1BNfg0vkL1zsrsNWQ2bt+jI3eA0Z0ktw7MrOu0Ktuqc8LYyyfQI+vFQL0MoaCnLohdtGdr/WIIiCVQag/tVBM9aSHqKiDQT8hSVETwIdBh+gtXz/HLzB4pn4MKuFJ/fDzfEatSj8Gwn6A/FpmuhZqxgs03qdtrE71vUK1uIiVxjIGoANnSN1bHFBXq4uZVko/OeyzRozabZiRQ2QifC9HirkB5UNG+ZkG9gWKpnJ8irmw/hXNSltpMPxNF8tcQtkhSLkFRgE6L4bx9l+eZ9dhdm8BiOxH2gYCoXP13u5HyBMjgyEDgddoqGbC0HhvSfzGPzdgBlGoL6TpGbBe76xMKsvdKrj/WH9lZSV9mpiNsE+CunJc5vgX1XReVchaj+iWemB8b3ifQlzPnQLCAAhEfMikuGrxysgcGCfLcoP+1gmc3EnrGhuby9343wZ5UuFLR9nip+Q94HoF3jkLIEmto1juNBKhENQrLobdRiilEa/uNYkMNr+69LV+R2bITe/9ZElQDkMD5BPhrSyCWe5hVOCYhydH62YQdqjZs2e2O+20zui7APfnlQpXPxNXMyZMQxnV4Rsqht4X7POsv53P3pm0u1nup9fwUi2QKb5SoK/K1rDByyp4hJDOJGNWC8iYDP0dlWocY3aNFtg9mxUyWC8iZoZvLfAvaETIYIQjxJRpbweP9oz7u4O9fs7LJxEkm2DJ8JyAKaxtoH2wkIn1fnV+6KRUJPYfn7pByriffn7fHnblQA/uWv90JvIagn,iv:kz6eoH7Lpn/k8659fSuyK/yKKhe1ZHjVlBx+spHSrQI=,tag:aqQHIhNIJn/NpzODxjFqVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ3BkeWVUdmhVSG1ZMTl4
            bWhPeHo1c3RsRUZweXFWQlgrUFUwM2I5N0dRCnArdWtwNFI3YlJ6M29MaEljdE1x
            THJwQ1EwblJ2S2E5VGs3R3JJZkhUbHcKLS0tIEtwbkpxbS9Sdys4K3B3L1BCQjVL
            QWc2L0dlb3dxbHFvWGVNYkI1RzkxQ3MK2tEdb9pBGm6eGjHuifU37vWNC0NEH6rt
            lUc3t3Uchcn2y28f088+jWHVZ/fgR9KR/SLOek1TXaNzruMQbSto0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-14T23:02:09Z"
    mac: ENC[AES256_GCM,data:WUL0GwiSO15PRJg8gjHa7ydpY9kcN3l1YSNmaFyUIvLgo1FeRRIpY3EHigM4TI21XfwrBy7+UV14EmudHu/zUJUXFSNnz168H9tJphPUPoq/iV0qDwsj3vJSv0HgqFH3OB0c3kBurp+DRADdtixWfSBuKzv0X6RSZfOJtZ1tlYA=,iv:WU8/8L42qyIOfI+V5yKXY3kb21zecY9luELYo7wn3g8=,tag:fyWR5QynsFxSC3CEHqMD+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
