---
- hosts:
    - master
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Install provisioning dependencies
      apt: name=lxc-dev

    - name: Install provisioning dependencies
      apt: name=python-lxc
    - name: Delete a container
      community.general.lxd_container:
        name: "{{ item }}"
        state: absent
        type: virtual-machine
      loop:
        - k8s1
        - k8s2
        - k8s3
        - k8s4
        - k8s5
        - k8s6
