---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Create Default Profile
      community.general.lxd_profile:
        merge_profile: true
        name: default
        state: present
        config: {
          inux.kernel_modules: rbd,bridge,br_netfilter,ip_tables,ip6_tables,ip_vs,netlink_diag,nf_nat,overlay,xt_conntrack
          raw.lxc: "lxc.kmsg=1 lxc.aa_profile = unconfined\nlxc.cgroup.devices.allow = a\nlxc.mount.auto=proc:rw sys:rw\nlxc.cap.drop = "
          security.nesting: "true"
          security.privileged: "true"}
        description: Default LXD Profile
        devices:
          eth0:
            parent: br0
            type: nic
          root:
            path: /
            pool: dir-pool
            type: disk
    - name: Create Virtual Machines
      community.general.lxd_container:
        name: "{{ inventory_hostname }}"
        type: virtual-machine
        state: started
        ignore_volatile_options: true
        wait_for_ipv4_addresses: true
        profiles: ["default"]
        container_command: |
          dnf -y update
          dnf -y install vim lxc-dev selinux-policy firewalld 
        source:
          protocol: simplestreams
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          alias: fedora/36
        timeout: 600
    - name: Restart containers
      community.general.lxd_container:
        name: "{{ inventory_hostname }}"
        state: restarted
        type: virtual-machine