lxd:
  children:
    lxd-master:
      hosts:
        server1.lab:
          ansible_host: 172.16.70.10
    lxd-workers:
      hosts:
        server2.lab:
          ansible_host: 172.16.70.20
        server3.lab:
          ansible_host: 172.16.70.30
