---
kubernetes:
  children:
    metal:
      hosts:
        server1:
          ansible_host: 172.16.70.10
        server2:
          ansible_host: 172.16.70.20
        server3:
          ansible_host: 172.16.70.30
