kubernetes:
  children:
    bare_metal:
      hosts:
        server1.lab:
          ansible_host: 172.16.70.10
        server2.lab:
          ansible_host: 172.16.70.20
        server3.lab:
          ansible_host: 172.16.70.30