---
access_control:
  default_policy: one_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]

  rules:
    - domain:
        - "lidarr.${SECRET_PUBLIC_DOMAIN}"
        - "prowlarr.${SECRET_PUBLIC_DOMAIN}"
        - "readarr.${SECRET_PUBLIC_DOMAIN}"
        - "radarr.${SECRET_PUBLIC_DOMAIN}"
        - "radarr-uhd.${SECRET_PUBLIC_DOMAIN}"
        - "sabnzbd.${SECRET_PUBLIC_DOMAIN}"
        - "sonarr.${SECRET_PUBLIC_DOMAIN}"
        - "sonarr-uhd.${SECRET_PUBLIC_DOMAIN}"
      policy: bypass
      resources: ["^/api([?/].*)?$"]

    - domain: "*.${SECRET_PUBLIC_DOMAIN}"
      policy: bypass
      networks: ["internal"]
