# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:yjisdiq2enVtNuZdE5u2B8XDmnS+AS3zoQThAC/J0duoWam1XQ==,iv:H9D+YnqJfD2a2jpNthVbIhjYWAQSEEOv+FzZIcS6Vy8=,tag:O95/kzYoYKWs/VjTjp7iFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMDRLNU1nMUx1V1FWaCtH
            Y0pQMXhLVG52cmlyenp5cGdMZTJYaVZNZGc0CjB2eFhBa1BPRXZqMGlqWFFKaFJp
            c3YwTXpTaVhmRlAyY0NaVC9Xcm91NWsKLS0tIHRWRkVqMnl3NkJncmJpeTBvRFFF
            aUxNQjJtdm1PLzl5NmhlWEQ3ekh4dVUKuJHehMqzRW8sagqjycpcNvY42hQc0E30
            AkR8+UHWGKWKiEKnU0LvL1Dv0j+GtzJvVuPZCvMU7oGOvfPv8fbbew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-20T16:01:30Z"
    mac: ENC[AES256_GCM,data:RJzVJywDAEc85uMCrerhHe9hHIXcRVfodF06cylPEl6Dk7Q47lirZ8kgtNosCl17BehvgPWwGgAIFAW9T6gfeqve6DhOM+q7Qi4f0nVU4yRHklAFDU58jq+mo4aXkpW1ASllX5lJxH6Y9eLLFnhZe2858cgAUNt0wdjxHKnRXF4=,iv:MQbE27wmJLGh3fDjT/81DV4T7PVb5NJ4cN1k1pB7In4=,tag:JfSj5auVC+rSOt0XdFn1sA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
