# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:389StWNhFOfvWGQQ5kHcohTuLw==,iv:htzqp0mJ4uU768FGToz7598F3DQGkKBh69vcXP+Ys9k=,tag:Smu4pvjPMXBXRxVymnBaQA==,type:str]
    api-key: ENC[AES256_GCM,data:AIZxexGXzChVwmvb+tZqOaSE+Kb5xI3ek64WEGg8VwDwIFKIHw==,iv:OgBqAEIaJJ188+qdfKRoXIge9lpa99+iU50KtYym1jY=,tag:jorOq/tfgciQGtQa2pjWQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWDBpc0JxMzNEZzVWRitm
            aUpEbTBKYS9jQVJvYi9tMGFoMVVrTWp4Ym13ClE2KzVIMnBYN3Rxa3ZqQmNCVE9w
            QkZPTVdGVjk3MlBmUDJZSmc0TWVSZTQKLS0tIFV6Z1p6aHUxa2wzTzRvU0F6MVFI
            OGQxckhaNi83RS9NcHd2aTdDQ1g3cmsKgHlXIJNOxbhFpE5VSK+BE3oWJ3Jqm5Rw
            hByfl/AOwPq6mLIh6N6IuH+W2Cxr1dp9JXdUx4wjhsGCa5OB/DW1sA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-02T23:29:20Z"
    mac: ENC[AES256_GCM,data:y+IH1x2sttfnmANNIqmfymnB3RlMdoBIuUEqo0E/ppgKm6SI5xljWknFLyCBG+JdwrW2tsvbPnkkuv58mm9BmPFS7FmILOYWSNdg9gOfZP8uoVFwETgMxMKXQwcXWysrg+ncg7+y/VqpGy8eqQrwsXrXAE97Pp5eFOdeBBJV3rU=,iv:GGPgFeeFTN4sYODIq1hW54gEuMnOo121p6SehLTMj8Y=,tag:i8q2v50STRIMBss0N5pNsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
