# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:A08vSffIDot9NTs9cz8S8aN3UQ==,iv:Scanfv5Xgpw9hA1cuXicRi3fAEjKN0IxtNIdYM1ZQug=,tag:8/npeRrWu5/hCpM/5Ci2hg==,type:str]
    api-key: ENC[AES256_GCM,data:TT2C/03BTzzxmml8gnTErUSu1rCZgdTlbga2pRygZq3gv3Sj4A==,iv:oeVacxkrf0YmDxz7a69AlIE3alYQMZ2l06haqs6BQ9A=,tag:lSA+HDpmi8HFUwenG1ftWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQ2RzLzdzRGVOdWVnZ0pC
            b2pGOVplNXByeVJZY0NIWUxRdWY0K3dBV200CmRZMkNVcCsvSnBhdXNZMWo0TTd4
            aDZXSVJNWEVkNmlkV0x2YWFVTlptMjAKLS0tIHNxQjY2SWlueTFRMG5ZdjJ0MkV0
            bUJtNjBzV2JKYmxTUXp1UFBGKzZUUmcKDqDe+xh0ECLL/n9AgLZMwAW9MNKa3zJ7
            5y3b5DVurg2XgaIRUbKrD5bVNzMDAzc8rpB+eDLC1+JbiBJs+giQxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T03:56:13Z"
    mac: ENC[AES256_GCM,data:ZMkZLCJ+r3ADOyust61vUDyk4D7MOhu5v/D3EeK58C4/a60lHEZVElkXejG1snDpDS+ey09NzppBoAcfsAREuvNywXoi7PlsFMdO8GUghH75wNbXf8SvmvmF5GqMmmFT3F3zVoGplRAmMuIrVY0ufmPulklB1HLX2bro6tbCDFc=,iv:/p5kwbgUqXa3gxYExdLgNYh59NkqJwjsiPXnypsJZk4=,tag:aEkWYFwpUpd5gPpmYnzzPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
