# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:IL1Jnoh1XI+M7BjSothuPgrkhg==,iv:nyetqb11T9gvEeorCfSlrj5b+HLcS4hdz+jNIck+htE=,tag:cDmTKHjTXj6ZDPYiZiLtxw==,type:str]
    api-key: ENC[AES256_GCM,data:3a3s20xkTLmjUzp1jCo1Jy01IO8mKullOMYOQWNz3OPUcZTVIQ==,iv:m7sGnBqWPDb/fHttTSt/6k4uA4iwOPM8VEZfYrw471Y=,tag:IP0lpfkAqC7BeWd/td9ARA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxckdxWWozUkl6dFNFUlNO
            NzB1Nks5dnJ3S0dJclRhbEQvSHNDUjNzaG1zCnlqaWFuT2xibWovUmllM21YRU4z
            RGlwUnhiTG5pZzhjZWQ0T2QwYXVBTncKLS0tIDhTV0h0SU5WcDVaQms1WnNjZlg4
            T3p3K1E4UVY4RlJaVWk4ZXBFUTk0c0kKqMZkyRY8VZlcJRjgXJ5PKDomqOigVmVj
            D4Hi9Fa5M9efMh83EyaA5VW6qpCWxtVeY6LyriYNUWHMKxOkiRdsOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-04T22:22:27Z"
    mac: ENC[AES256_GCM,data:aP9r4bGZ7+f8PrzDaJBbc1XXZHSETdZ3XKXhsyc/kkAPj7o94F8Jdh0oP6KHHI9bVn1j8opO1iiju57fTBHHnNUry3YOtLjJV1VQ7RLEg6JP3xyD4nRHL7scQ0tQPgZ4hISXUz8+aFOoXzIuwEbuZDz9I77KLGYb9OJ2ABpq+KA=,iv:vxF2H9E5z5XfXRXaz6jI81KEmq7tcZsWXJblaJe2UbA=,tag:ZGQVArCdEIuFxKhQBCpNyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
