# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:i8wmdyUhHdqYPcXHfrG66YUoJw==,iv:51bcI4eMfHc3Ww8FB317ygNJiP6Fq0pfhKwRA3msv/w=,tag:7LKjA3elkEzjSVX/3+nmCQ==,type:str]
    api-key: ENC[AES256_GCM,data:EQw2Zc+2yIsDyt2Rcwhi9mVj3cbBTmMngqyo7V1NkE7rPyuzOg==,iv:c/VSTlWEN/MM1KlGVCnWBk4DrGBg0Ai2QcQoY4/i6Dc=,tag:OkdcOQGNsGS8HqrlyG83LQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM0NlT2ZMam5WUmx2NGs4
            SXhkUVhESy9JRjFZdVpwSnVpR3FiUXE0b0ZVCmFtVitvMDFzTFlPLzJWRHB2TGZM
            NUNnZjE2aGpzL1lCS0ovTFYvdERERlkKLS0tIEc0ZzMzQUhKSGpPc0hya3pZczc3
            bGZNQ0FSS05sSzBmN3FVcFMzU3phcFEKG06wRQ6Vy3Am1zdGVpKNUbo4iM7yh5D6
            vTribUNLlrLVjfDdtmpAZQcFOOseoV/Svn8o3mPt0467F15k8d3PWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-07T03:20:15Z"
    mac: ENC[AES256_GCM,data:wxibnSmaAJ3L07bG4G5Oo4ZgmbH26USjDMhk4KzbtM5vN5Urf3/nAyNlAcj45gt+NKj2oxvZU/XzXTYqNCVxeww4FGJ+OXTASsbtOgeBCjj5MLVMcpsC8OxdME2G+Eaezbi5PLhuB6+iinVg2xrJP5wteJSs8Xi2KI4DdP7gXyM=,iv:Y+cL/8LCT6CfY6hdYJ+C4maeaR3uH7wcg026GW9nlGc=,tag:yyGLB6Jx1/+ci56huywU2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
