---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  METALLB_LB_RANGE: 172.16.70.100-172.16.70.110
  METALLB_K8S_GATEWAY_ADDR: 172.16.70.100
  METALLB_INGRESS_ADDR: 172.16.70.105
  CONFIG_TRAEFIK_IP: 172.16.70.120
