# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:jtm2G6WQlnxa9la/,iv:rTO/HiKXLZhijX0mkaqIZZcUhwO6naen06drEWFKLrI=,tag:aJV9LrmRbwhkVHzApB0VUA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zVh3hspr0IbyczcTbUF1oGSl8Q==,iv:ccdmadifUChi01mM54JdEF+S1W3eP3CiMPHqXd+2VHo=,tag:DIU9HGJCUjrqsudlmygtaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTLzltTlY2aVFkR2dxdUdR
            UHRNeWRpT2xxdmo1QkVvUG0rcHhWQzIwZVE0CjAwWnlVbFU4TVhQOXBzS2F0SVV6
            WXNMV3NaaEFJQ0ZBR0hYeDNXcTVEUlEKLS0tIFVUdEl5OUNyTUhETzlaQzN6YzND
            dHlCL3N5djJPS0RQSUoxdEN1OXhpMVUKi+7rNMq30KP9nfj1VbwYgZF3wpiVlqE/
            YNJxlKlVnMcQuIIsK/VWouUBOgCj3nklIqNvIp4Y0FQjRQz8ZUqssg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T03:56:13Z"
    mac: ENC[AES256_GCM,data:C5CWl9S5WQeNGJ/0+5YAduJ/U9ExaUwro9jYsYMM2oB3V8jwuGafA5/eFWWRTgT/k9bFpsdLIUXB9vE2/DVVHgJubtPHufzJAbqCtutXlDpnkT3qAnnIOHWF0FO4yj2FRC9LAnzaYrksTkmBQLPHXl1nNd0WvmwCWW/ozk2tYK8=,iv:y1jQHn9urvN+GqwbPNHIZVFNbc3k1N8QIhQwuR2m3zw=,tag:U8krVXSPzHLH1iHLBFRRVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
