---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  METALLB_LB_RANGE: 172.16.70.50-172.16.70.60
  METALLB_K8S_GATEWAY_ADDR: 172.16.70.50
  METALLB_INGRESS_ADDR: 175.16.70.51
