# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:f4rQa5XFJ8PCvw7y,iv:6nkN2/wOYMEXBdfby9qN1fM75h+EC3WZl461+zXOTQg=,tag:9hv8sonniJOoxBWsaWy9QQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:HZ+fgCzuqBXXN/H7sa3skWMflw==,iv:pIiaCCiTLZ8RHiEwqYb9eeYqBc9BwOksrvaJe8PudoQ=,tag:3RttNqUQuP8Bx9OV0vxZNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFS1daMlBWOWZnZm4zTnRI
            OGtZSHpUUndzaDF2NFFEL0Q5UFNzRVI1ZjNVCkU3NitMTFZXcGF0bmFpd05KeXRD
            dU5zNTlCQzQ3ekdoL05DL3gvMUY2Rm8KLS0tIHR3K09rSTNiT0RKRzMweGxsTW9V
            UXZYNWw0dVVhc2JZVmFzOENvdUpERTQK1ktQxQOBuQ+weWfHm/DNgsRwlsbi/UZA
            Pxc+uPohhQAc2Rtv0klCtuVf6iHJoCndziSn6sRYHcN0WWOW7vkWCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-04T06:32:16Z"
    mac: ENC[AES256_GCM,data:G3EraLlViuOL5gAVk6Nkt6AEF3+73F78hOn6OhwjZWiaRKUdxhf3lj1EwIVO9WMUJAIH4rH/0xyBnT+YkS1WYrgxLvXznsT8wjdV8xZnkMr8K+pBQS2sSpGi1ZwF27NnoMlyC5DFRP6JxN46gSD7SA8AEE5zsywZTMdBuVrHR8I=,iv:2Yv4yX+/6TqpNZBlhTFOk7Eh6nvLpbRnLzOWF9oGyjE=,tag:dZju9Otyjh1usIAv67AMdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
