# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:jtm2G6WQlnxa9la/,iv:rTO/HiKXLZhijX0mkaqIZZcUhwO6naen06drEWFKLrI=,tag:aJV9LrmRbwhkVHzApB0VUA==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:7H9eIvBnb342Gu0u,iv:jZzKgkOdjmInISgwKCmuF1g9h5MNDrldxFR2Z8pB0i4=,tag:SI9Ko7Yx4mKuT0Qzz2Fdtw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zVh3hspr0IbyczcTbUF1oGSl8Q==,iv:ccdmadifUChi01mM54JdEF+S1W3eP3CiMPHqXd+2VHo=,tag:DIU9HGJCUjrqsudlmygtaQ==,type:str]
    SECRET_EMAIL_DOMAIN: ENC[AES256_GCM,data:ECgdStLezj8fnATX,iv:xLw0oE3gLLZxt4iVGdyrK0Ymct+IB2sk4AytgSvn4+s=,tag:z/f8EHWNygDuNSe2b5iKSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTLzltTlY2aVFkR2dxdUdR
            UHRNeWRpT2xxdmo1QkVvUG0rcHhWQzIwZVE0CjAwWnlVbFU4TVhQOXBzS2F0SVV6
            WXNMV3NaaEFJQ0ZBR0hYeDNXcTVEUlEKLS0tIFVUdEl5OUNyTUhETzlaQzN6YzND
            dHlCL3N5djJPS0RQSUoxdEN1OXhpMVUKi+7rNMq30KP9nfj1VbwYgZF3wpiVlqE/
            YNJxlKlVnMcQuIIsK/VWouUBOgCj3nklIqNvIp4Y0FQjRQz8ZUqssg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T14:45:53Z"
    mac: ENC[AES256_GCM,data:eMe4hcxVPdYlnxD4jM0d+m466M1WPMGCqqttGLnMDkSWPfuV1gCmvA2lLi7McMSWpBNqisdSPP6Poiw/5TvOYkQlXjLIXkYti/Qr+/HOv7+Y3rcNQ1ueTgJh/QNHZGFBrNmJ/NS2RHel4TArXprOqx6VkZezfDkb1rLkJPZNBss=,iv:SawwzjAe3SfwJXGUTNqPKTFPJgG09845FxrZWXT3Ne4=,tag:6hrztEGW306RmL13icwzjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
