# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:uxzSezaAamzS9tG7,iv:eVvbHDmO04R8PeYMM9P96TNlhwT0jJ45GnTxRoUafK0=,tag:IVFPqm50w2WqAVa9AEJKXw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:7vmLHjMO9omvr7+Rr0jvngZ+IA==,iv:HlakhPoB3caFelgHcIBMQcINM10/75+3Ba9tQWu1A2s=,tag:a5OMvFMxEWpBpqZPKSY8Fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMGRKZzIvalZxb2hFZGJx
            VVl3dG9FZ1J1V21Ec0RwYmRKSS9LMXdYcm5JClpRYlR1V29HQVhFMXdPWUluZVQy
            MVRsTEdNMkZ3eWgxUmtsUU1yb0M0RTgKLS0tIFFtZmx2QUdlMEgyYVlTM3ZEa29u
            Y3BsMnEvKzlFRTdyWUtnMjdleE5CdUEKZYBXAsN3+1QQHTy9xMZK8AFR+enDNJjW
            pyBsAbck8WrLeLmDmDpcGoWxdhnY3GRS2qI+4IlE6xeDWc9F04SqCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-06T01:06:08Z"
    mac: ENC[AES256_GCM,data:aEvhgBwqMkcqBknptinBV2mJESa1jJpqlshwXFk/Hmt0q/ovf6mjbDu5dmyhfq+d4qSUY6C9fgmjB05HsshBHXNxLwISXmg/1wS64NC/JJqfLwKH72cM6zjyNHX0m2N8Zom9OyuLLk3S76BMK5hCM4uJS+qkjg9rbpAD0ukxEcU=,iv:myvYRs3B8A6rN8wUHLbd0xjgIkAyRi/xlgLn5hSqokI=,tag:s99JNG8VWsryFc6d81UVSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
