---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  METALLB_LB_RANGE: 10.65.124.100-10.65.124.110
  METALLB_K8S_GATEWAY_ADDR: 10.65.124.100
  METALLB_INGRESS_ADDR: 10.65.124.105
