kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: frigate
    namespace: default
stringData:
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:enzZBA==,iv:nlamT0VqM4xPrMCWOKEjZijFbUEWFPYHVd2JnBQ3Q3c=,tag:C05BqfI9p9Oh1usNJzzyZw==,type:str]
    PLUS_API_KEY: ENC[AES256_GCM,data:uHwbhNwCSiKOyQW/5or/JHqXV7HnuJOwF5l3C0a20KUzMaCIF5bqEI9N0FiLAAZ5GSHsRDCj6WowST/UbI524sQgVle0Ngoprz67rSc=,iv:TaurMCFpsbRFAu63dm3eg2SGAs41EH+eC46VCSEUpN4=,tag:x4rFaTpMPzWjIz0DitjEMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkU2JyTklTL3NBUUVWem0y
            UmFwK3NxSDA2M3JubVZvbUxZMitzUXU5c2xzCmxUL2VDamRRN3g5dVJWU0wxM3Rt
            WXYwakFTQWRXc21aTkJOZ29QR2N4Y28KLS0tIGFEVnc0cngxeE9DM3pCcDVGNXl6
            WFFiV1ZPcVhURC8zb3dVTGkvNWNQN3cKur3r4+Pl79RX2GlA5Yvela+8fOyBdI16
            jmxOHT1BrO86fADa9fKma9F+2cVuWuddHP3BeqIf34bLgcT2XV62+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-18T18:49:16Z"
    mac: ENC[AES256_GCM,data:NuU3n+CkL7jzYD3DIM7wv/auS6O2JJvrxUg+ZQTwih5lVgaWRf7pNIAwYm1CnAc4kS5l9IuHZX7NOcd9jeUrrNAmXyEByGQsA+MpNK9paZWcNiEpT3KVMkV+YEF4oM1Q8kn4Z4Oa17NxKvjiOtU34KBhdRRpO+PfaTKj1sOPSFQ=,iv:YEMqKr6ngDJTi2qqay/g3QR7DT3y6L9+qS/0Q7SwL4U=,tag:9rA8Gg1ptx8Q98VwUjUpgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
