kind: Secret
ansible_user: ENC[AES256_GCM,data:JMC3hKj+ifAr,iv:z1oHjOaNE/FhFpLVp3yCmzDACiStve9F4uftw1dd7kE=,tag:4eOG6n52FHdE7hxtDTUU1Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:GdFUQh7mDmU=,iv:L2GxhOo3d4A+VTUWins6GsvMAp101pn6Npu/L8yEtCk=,tag:4wHyOzSJuYVWaIBnu03QAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdC84YW9SWnZBWDJUZThF
            NjBNdkhtSUROTnpUVHpQNjVGSUwzY2RLVzFjCmRqSU1rcUwzc2lRc1lZMmMwaDZG
            WFhzaFFFaTdGcllFU0JtM2s1RkRWK1UKLS0tIFdqeHBieU1iaXpUYTZmT254QXhO
            STRmSUpBbHhSN0t4QkRBV3hhVXh0T1EKTTeseoXJyUAHfV1Li0Uz22AMvGUYdMfp
            GvRsz5VTG+KCmBkvVE8EkvJs+qvI6kxoL5sv0CfbQ722/m7/jTuF0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-05T21:35:40Z"
    mac: ENC[AES256_GCM,data:3wbgOR5kADk82SsFTkn8BF960j6zaS3wtGeqVQHshW6OE8RTg9hCJXyNUt7vZwsUMr2fPuknF/KM06LdP2dQczx6wYOZgJ//kos+AcMZmd36BklVtbfeCPFJEU8y4gzUBPDIH9E5m3O5XVzgttM0pSfjr3N+lYiDfawV+Qizpf8=,iv:/g7prqZ9S13ic7CJVOJl27DKhELF1KwxQpsk3xfNuDw=,tag:N9dVucMfY0zoDajU0UxDDw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
