kind: Secret
ansible_user: ENC[AES256_GCM,data:9wyb79hrvpsD,iv:Vy0294QV8S/1UcN2bY2zZU0twBjDEAER/r1J9Gel3X0=,tag:PEDU+5lrXCqSK3jrTuhcDw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:wd7QWhM9Khw=,iv:e/TZ2IvurG8QU/1ZGZAL877fC+idVZ4XydmEmj9wx5s=,tag:1M6vSm1DvikkW5r5gct4Zw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dmplWmFwaFZreURGcWxD
            Sk54TDVVNGhmNndxc09Xb1JkR3hSNnJqV2x3CmcvODZUMG9COXJGWHlYNElkdEdU
            bWk1T1N3TGx5dWY4UnpFWHFEcVl5ajAKLS0tIGZhcG9LTjdPMkFyaE5zc0E0Szdm
            VzFFbEpEQWl5TzlaLzBzOEdzY0gyR00KxsY1K26JcHkQ71Nc9GpkylW7fRC6wgMi
            Da0efPiwZ+QbrtpM4PyQhxb+Mh+mtKKvX1HS8jAYUN/10J1Vyf2ZSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-08T21:43:39Z"
    mac: ENC[AES256_GCM,data:Qq6jJsjcpzdwk1wrqaJrxIzf64OzWHARw8Xn0obSfJj9v0bC1ppCXiVQ6MDTnFpsjmNvZowHsr2so3Sa1ey0lZc2FubsNH851RxetSmFd6EmZl5b50lPgrqN8KBVy3xXnI+fQQ48z8xEU5sDXmNnuXavgdSfutbediD6lOAv5JU=,iv:u/tvoF/HuDzrCrA9gNk69EtJ9jneeg2eEhtM6S7UkaE=,tag:o5pCAG39VNhFN06dNUdTzw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
