kind: Secret
ansible_user: ENC[AES256_GCM,data:iMLmgM+cxTY5,iv:GQ0DmjYR/rtUVslt8V9I4TTQZtN1ts+KZRQYvOTz91U=,tag:cle/Nx/2mTsLCwSNmvWA7w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:iz4Fhkspcks=,iv:xvwT+Qrk903yOAkgGcpdHBVqTred6f4FcS0U2pqTbqU=,tag:gZ379Nbc18qca6WBtpRhOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMk55cURGV2Vzam5hbmpS
            SGludGMyZ294bnVnVGtjcmYrbElQUEY4N25NClFkWjJTSzNUR1FNaHEzOHdUWk8w
            US9INkw3YXVBa1ErUFpqQURmUzJia2MKLS0tIE1XQ013ck5ZVkNNODhjOU5UWXdh
            TkU3akVFNmI0cjVKSm5pQ2h5NGtBRlkKF/G1BzG5gqgIfeDLbirkCQ/ZrVcHlu+j
            o2Jgmus2u98iKQ0KGcZQmhtpqQbrvl2FgOheIZc3MDb4ZDY3V+7H0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-21T18:03:42Z"
    mac: ENC[AES256_GCM,data:LQY+Ow71ps5htDQvmu5r2lb66pVm/9LA/IUCDcwFJWHwa6oa7l4lGMXIZSAOBX7gpBXmiP19Wyu/NSVcp0gIVLUk0vQZcXEvmAXTkAZY3dgYOHmbz4jMHqPNWEF2zz7Izhv4naIh6X/C7KJTIHEoZyt05CAzEVAwAekTcrLsE+k=,iv:TQUT5GnTi1YzYhevtvM8H+zx19aHgGF7526yY4RFEko=,tag:HwFqkBAVMDavVslgXqlqPw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
