kind: Secret
ansible_user: ENC[AES256_GCM,data:MftLKCeRNKGK,iv:73u9Fdex1E1tMTXPymRJc5lpcIb2GFEgE9neGUKdRvg=,tag:3W43EFwLITwQr6IaVruGEw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:rS/8LbcDHno=,iv:Vd12r7sNPQXs0RqrGRLqfrvZPdVuiM+xjEiVVjkPZmY=,tag:FdQ7WaDyk9gkINi15FRivQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WHRIWVp0QXN3N0FHZmFI
            V0VJR0pGVHpSQjB5REdVOTVYdTdDYjJuYmpRCmtuaStJYUxHMHprWEJoNnJFZVBt
            TEdUczQzbWJMVlF6SFgwSFVpdWVHNHMKLS0tIEZiVWYyVlg0NHFTKzByRHlTTVRn
            UDhJWnZIWGVSUjNaM3d0aVoyZnd4ancK9X4oaJIcSj1Vs0xqLLBkT0KIqzeAehnm
            5OEdivJGuJ8UyMgbvTM6iatYnWdDSa8ir3n0AwhzHvZJ+2V06ZilrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-07T01:51:23Z"
    mac: ENC[AES256_GCM,data:QQemiggotKirdNyTMpRpKDtia5uptNR0DwTsWl81kjjThSo3SKQngp8fy5pNJ3LB2xpNHwAQe6++vnNxilNb/naFhNlRCQROwM7OF52Li04vrdQ5izhR99p8Hh8K09/I8rnlYxEYjIXmZCa/KzqLBVem9nKLA9cDhpH0K1J2Q/U=,iv:VcTYrRF4XiMQp8gLuO/nddGDNTDcRBsRkAqVuhknMS0=,tag:h2lG2nr+/y5DUyZbYkSR6A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
