kind: Secret
ansible_user: ENC[AES256_GCM,data:UeeHEbkFCsMg,iv:MDGOuR6se6+A4aroG6WTq/JV3K9M9PZ80wn3QOSVBmo=,tag:CMUCC3Dtg8YkOuF/TPBn6A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:MMnpqxFKNe8=,iv:O526zAqIjvrXJXqKXRmdwEEz8LASV0Alqtg9I3Pxvdc=,tag:9qPtarSomvykMOFDESM5wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TlRwb05YUG9wL3dWT1BK
            dlY0REFRdGZ5YkRBT3c1NkVpWUdnVTlNa0dJCkF0VDk5RjRPZ1pRUmpBVVBhbllq
            aFdhKzlRbG9KcEdZQkRwbzUxVjRZckUKLS0tIHN1Q1dxTjYyZDhjeHo5aUI3Z2J6
            dUFxZWN6MVBWREx1ZStod0YzQ1BCU2MKkX9M9VlW0cXRSBsbSI+wDK5lZ/ymrfc3
            +QYZ967/aewTSr1zh8hbO7NZOzLxSfnGWEKPvpD0Sg+9Nan8M26FNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-06T01:06:08Z"
    mac: ENC[AES256_GCM,data:1B0YVeMoHWSCguMLgm6BIN/hDRMwa8GkimWSguh0r5U0L3QYZhlLHNtvXEF0DwIqXxIoQFrjzI4bg/aNQOQqUsPyoNbOiFD2Md7abJMS8b+qCMH1AcNVoQ0XFT+IlnxpUZKKdkuPh7SD5fBHZPl4u6635CdJf/ujRlP7OFmbIWY=,iv:Pv/buEV/2rvOpSRqNOU6OK3mgsrdp3bzCulWBaSK6sU=,tag:5OeX22nVSflgeIWQw7lrZA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
