kind: Secret
ansible_user: ENC[AES256_GCM,data:S7SeST7EgYxM,iv:YhQpD3HSnUD65nzCjDpgoh2lWIYnGPGC4KNqGreEuDQ=,tag:2HVNDSXzls1Tweq6/UzlGA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:jCYWMss2OG8=,iv:mziIG9XEc3o9DJzOkh7jPzETL+F7gOmqxh8O7aWl/h8=,tag:mJW3L3x7BwRyF32gKX3hRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpa2NPVHN3V1ZGVmE5RmVt
            TnRodzZMNkp4SmtUc3BmUDhObTlpVU94eUcwCnNWbUh2TzVhZEVZenFSV2cyT3Fp
            YXhNL0ZqOUlrcUJVU1RuVWY5U0ZkV0UKLS0tIGQyNzE5Nzh4N0xsdTlIaWdJZ05w
            bERya3lRZEh2RFpuNUtKL2pZSHpJWnMKFY4yuD1/+vlzcjMQ+JG93ftKcL4YwXZs
            3zbLSBX1Hf3u3sY3X6urTBVspybyCJzv2vtKNdU2gIg+484rWDSrEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-03T23:42:47Z"
    mac: ENC[AES256_GCM,data:G8fAyeu+SwzSMU+xoTsZ8Idp/h3Ll0xKsskeeX7KI/CARNGa5vivGwsNrVLJgE95INnhdutQ2FFc/67b+1Sg952UFkUuqciJYkb+LSuSj7f4T6tUmwUJnvVdtJcKNAFKrmdasdfX7vOjW8MCXJZNvWB2WSTiLOKENttwX5Xo9cM=,iv:mPGgNLHZ92Q/7ryFOqDR25cDtrCcZgM5ooRup4B5ilM=,tag:fT5zaRaArArbbjWMKOQgmA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
