kind: Secret
ansible_user: ENC[AES256_GCM,data:4Mer1a5mORDl,iv:7PIvJGvhKQliHputwAuT3YJ5ENgrY2CP2qWzGnem09k=,tag:VEnVYvsczjO3l4B7+lGC8A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:84MYEHV/F5A=,iv:UZwH4W+Z86x8AjmtvVMXCmWtNW4CY86ONz7ib1yu29Q=,tag:zKUrd3xRtrVXiYYueyOYEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS1NVa21md3hub0oxV1VT
            amRjV2NhTHZ3R1JMblNEVFllMkJNNHVDZWhZCjg4SGl4M3BQVzVXRVJ3eEUxOW9C
            cVpTRTgrODdtSUFlczhuUjM3TVhqdFEKLS0tIEN6OVpqbWRRWWhBb3ZERTFZN3l1
            SEg5TjJQN2tVRm0rSk5kbEpPNkxSakEKZGsekSy3fakwNmY519s7aNrjVOGEj/5D
            /zBZaaIAUKlmRay+AxfUSELrJSDqkexcbCTjYeE+fe5cyERSQ8V7Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-07T03:20:15Z"
    mac: ENC[AES256_GCM,data:tCO0h1W1i08jHZKBZ1fSrfQOZohQnk6gcbVk+OT8JFdhUBKtpSSRTo2+oBn5TKtJB4ZGM9V1AKCR2gg0fY4ppnCTwDlxMTl4R4u+UmID7tc83GQRcEiGtTB9qC7ZDkysCVzBE8vDTaEdQGHJuiM7Bm6c07sAMoW6uS4cr4ietxY=,iv:WhvTHrBSn+xRWxNSqc9WN82OApeAy4M+od01s1xC4+k=,tag:puSL4JTmY/Uu8Rx+4UEV8A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
