kind: Secret
ansible_user: ENC[AES256_GCM,data:metjHc596YKG,iv:183ZLnwXo70I191UrQU0r2sdrhtn7Jn2uFacw3d8TYw=,tag:yVF6PqPeTzagwzHPQDLwwQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:IYxeA6Ns2AE=,iv:4emmAA8lV8j8T7+H5s3cXsmKj2nK8x/nd6/GYme3VmQ=,tag:TzWQyEJcV0odPTmCEGh8Ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OSt5NS91L3FwTGpRN3h5
            ZkdmNGNwQ1hiZWtKR2dNZHQ0cnkyTlBpM2tjCmtBVFBZdEF0OXJEN3dOaHgzZE9H
            MzJaTWpuam1meU5wZ3J4RmlZN0JtU1UKLS0tIHpJeW5HMUlyQXg2QjdoVXBCRi80
            NVhFQnVRN1MvZytwQm1QcE40c0FNVWMK5sxThajKnlsiwQ0xqIM+YT/9s60Qyc+U
            rvDyx38n1f4KTDj+ADDavFGc2d3TilmCs8W6wdsJsoBQjbbC0D0/nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-04T22:22:28Z"
    mac: ENC[AES256_GCM,data:hgQHITo3Yq+C/QS/RrqfRhfD1Z7uLZ17mm6NAbW39dG1+0/muwHkHExK7ttvic19TsLyzz/lunvvX0AZOLnOuXsnYER0uiBoZC/cDpyBlJmjGrebHeoEstsy2A5JGMMPXGemSWiFXodZuOhhSBiApUJWpt2mrMl2aUEyy86DpDQ=,iv:Nihcnymmfn+3cTtvn/4cNKUMzlvDdpymPuP3UTq8Ac8=,tag:glAxxjg1WO24a2XKim73Sw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
