kind: Secret
ansible_user: ENC[AES256_GCM,data:Z7NvA/DIGPzF,iv:tbNx9zUTVgSyHAHvedxb4EJy2OJo015sE2zovkOBu+I=,tag:krSgVVUrswUBceMaSC7vjA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Lezqr4XMBMQ=,iv:FMZyHRpoxQuOzLk7JrHYA80vUbxgDNEE3Yu5y6PvtX0=,tag:4URL2pEXcPcu6nL+boUvTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbjZ4azVmSUw2czZqRW9v
            R3FYL0UyYmpDaFgxR2p0bHgvaWM3UWM2ZlNFCllBdmdoTGNBaW1RQUVLalFBTmJV
            VUY4ODNPVUptL0Jrd1NabXpldnQ0S0EKLS0tIHVvQlBDZTg0L0VGMnJRYitvaERi
            WkdwbDJFY3BlL1ZwVEdGNXdIVDlxUXcKWWMUXOI1j+eDDuyxXjNzpfa4VxsY6HAB
            M4tHQzLxxh9zj007IzyUP4ygc6JDUTIClEN7/oVpmMOIQ1Mt9C0RnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T03:56:13Z"
    mac: ENC[AES256_GCM,data:DItHhG298wklOoi+gZO7xqLB6sA8kmtyFRMLRWT/UMblVc98YAqGgiAYMo72jl7nqhmtdasijRfTTasbgVSQLVmlOrfyj2luGhDxVjVki92hCu4jyFU6B4S/bi+I/oEGLkPwq0e4MJXMvXjBSXN9fHdL+6fMtlFS81NScFF+LZY=,iv:dD34G6Kr+PLlQoYXlnhy9qpq6/sLct8o9GacnDANkgE=,tag:5WPMYr2Bygf2XwaNrtgNOw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
