kind: Secret
ansible_user: ENC[AES256_GCM,data:rcitns5iE7Oj,iv:lPfOApNLOxzqliqOevyi8r+/FJt/JOU3+tFjlFWHG+g=,tag:9rhunw+0O/hIxw56BeaaZg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:eshwltjqYzs=,iv:DqLitRgSuO0le5C5x0UBSL+DsJJ9ZY/mXZoo2NX0s2s=,tag:gY1oE5qu3nQFJ/h+9xFVUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaa2lrVGxERThxRFRvcFNy
            bmlmbnJiYXlpV3ZiY3FZUzJJSy9GbVdNWmhZCjN3dnVRWE42ODExelFGc3lxeUFl
            V0VBMElpaWxJWEZSMVBidUNabUgxRzgKLS0tIE8rclRmREFqYXJtUnIvVm1aTHNX
            amZublNiNEoxd1FhUVdRRmd5Z2ExZXcKTjs5rmODNES1wl6ggbMOtY7GBA504T36
            3MZNQAE/nqe9Y6ynB1P2tGpzb2Kzsr3jUGUDboNMh2aJWWy+vk1nkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-20T16:01:31Z"
    mac: ENC[AES256_GCM,data:1OHD2fIniTivQf+90lLvCeGkH65bl2+Wc3wgIZluJzY63UycY8BPMGnEIEhh63F9owXby0p+KsQodoWfEmMNn7XPqmkRt8hTbJrm8mC+nZlB3O7LrBw00GfWsJ/WwbZAEOR8j3MjvUtlgMPKCWbC0zQnsELc9tlq2Of/Yg95lMg=,iv:xDLR/7CYLwVjweGuT7DaseKr93JGqECnY9fLFRYbr74=,tag:HtczOOJWn1TDMvcp0q4gJQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
