kind: Secret
ansible_user: ENC[AES256_GCM,data:LYWtCBR3PeK4,iv:PG0BQ6KHJwkphuY95bQyjtWHrtRu0MbxEQwfqXAIA9E=,tag:2Gpdifs8Lgnm8lvPf2PIQg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:r7q8aj5xfH8=,iv:o2dSGhWiXKCNk3GFkY/rJ/CkmDVJlMwkeGO1KZKippA=,tag:lnELJE5YC83OJmcp7H09DA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMGRuV3hZSjhYSXlBaXRD
            RlcrSGpEV1F4ajJreUdvTjZJL3hMVHZpUWg4CmFOUWhBbGF0SmVqWjYzV2FZNFZZ
            NEwyTUdCL0tZendQUFk4UVZKUUhnODAKLS0tIDVNSnk3NFZHSGo5MkpML1VobGVJ
            eFlFbXp1RHdJN3Uxb0dMN1owTXhDbFkKcKpyuAchBGgWEwSRGfXpMuI5Oot+5uZF
            IS6E07NLsexml6/9YMnQW7x1Uvyw8Ma5fgekEsnL94NAx4EhJJB6Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-04T06:32:16Z"
    mac: ENC[AES256_GCM,data:4LqT4Z+aAS7z/dl1eNuU39kr0CRIvPC3EpVsmJBwa336saLU+9g87K497TqTvRZFr0S0DhjAvuntpgHdNs/vVBXhorQvXp4GIK+kCjT4m9k85S7vDVsNOlxmES1gYwBWHW7M4xBRr+djNtnf34q6dFnHP9FuEOLdxkBLAf2+HDc=,iv:QYl7OUAUObdR6FstE+doSV3w1x7a5vPRy8zUqPMaziA=,tag:uCN9+s6ybqvUTksVP4krqA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
