kind: Secret
ansible_user: ENC[AES256_GCM,data:KLjx/RcxOppo,iv:mA36dOa59x6EtP1ecW4h60NPcCI/hFxJgwrWKkcPmxo=,tag:SZ75eW1KIQFeTuA266HbiQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:LQO8sjHrgU8=,iv:H/4ABJ11mrohxKP8vIO/rCrfmylWQGWBohUtE64TCFc=,tag:nEKeLsNik5TBjMLTEL9ZEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUkxSSmdqTGpjeFNMdXpL
            M1pLcllTTmRYRTFXVkRMUi9JWkVUU0MyNnpFCiszdWIyZ1I1OW40RnJHNnVubVNH
            bkFqMUwrL1BOeTBvcm5GL0x4ZlJaWjgKLS0tIHV0bC9uQVlIa09BWUxFSUVRR1V3
            bURFTTRXQmk3WTF6UVlEaTdFR1lYNWsKN+8OdCo1mLYTA6tJ2hQcytI298lOEPKt
            m02cRd+bvLWrWuEuP4fE11R7qkZTNV4GAnsP8FUOLjHuFDvUcDo6yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-05T21:47:15Z"
    mac: ENC[AES256_GCM,data:dica+7Z0r/1RUMA5WAcHqdA6+C+NqL5Ro5mLSMP7JVeRhl9WOlYhhcWcm6TuXk899S0mzRwxzNk6FT3kGiTlvSrj234e/b43Lrrmy6ovc+9IXRFJB/s2E3Xd0Vqnc+Kjn+PmozszgCnLvJ+lci0v/GZBYWOwrPg+BZtl4XQsXWM=,iv:FNvLoKsdabS6Eh58zFUjVtE8nHfaF8BVpVD5MkCw96g=,tag:8WZjVd6gGDm0AszGmJ5lRA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
