kind: Secret
ansible_user: ENC[AES256_GCM,data:xmwW2RllVou8,iv:NWUq0CI+qdL9z+2FQXmL9tZPThK2ZhDTUDCKXW6NtG4=,tag:SRXBfdD3bN5QGqqd3BVMZQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Iy0JXTt5fyU=,iv:2IjS7bgl2k4UPf9Y+5AQJh4q/Nue3DSaoe06o1iIttI=,tag:ZkYn3UtGWkrBKtYxwb48OA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRa3NFdlB0VkQxejh4d2NM
            TENuTUd4UkZGbUZSRElPQWp6c2tNQ3A3NEdzCnZ4WUlLbUdFL0poR0RGUnBXLzFN
            c1NSMERJM3dtVVlrRXJ6TE92RVZ3SFUKLS0tIDZqQTRrRnZpZXM3eUozWEJ2ekly
            cG9tM0poY2UySFdPb0VTRE9WMmYyUHcKLZJ4jeJ9uv7uzOT3mhlDzSO/o11aIl9y
            qTKHM20C0S9YcKhEQ9srSfRBdMbdSHBuGcMXjFE1prWpw03ewsyfSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-08T21:43:39Z"
    mac: ENC[AES256_GCM,data:FI9/ppavhywoLmOXGc6V8VRAIxvQDp2FKulHEf9u/Vo50VuOHnNVP1zG9GTKomlfnu/7owrY1DPb5yIU9LfyfekBtt5tHcbzCxMqW+4fdxdlyeEFdjc609qBUAp1pR6FmZ8ag6ceejRO+ENM1/IuSseXLyZQffuXJqxq7OwILas=,iv:7P5nNnNlvWVuJ/E2gXoRWL5o86EzovS5XJ+6rfQtXvs=,tag:gyYaGiQJo95Cd5q15I/28Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
