kind: Secret
ansible_user: ENC[AES256_GCM,data:YQxV+SX9EV3d,iv:pj4cjfa7t3UELslDkiZK+I7XXUaIE7yyz14LQK8bxe0=,tag:HQqC8nw5n/dKBhbNmt39+g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:iTlugSEdtJo=,iv:ZP0B1e16TQEkY/3T8qD/7V0rmPhU/EzrdAkljccR+2I=,tag:EbUq4xPITRVBxJVqmiTukg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK2RaSGtiblorNjQ2c2Y4
            NFM2ZW95K0lONUtJU05saUtUV3FReGhCV1JFCm96STdveXFNLzRZUzJJaTFEQXBD
            Y05qaWNHS09LazE5UVJ5VkR0UXhkNGMKLS0tIExUdmRiUWxVZmRENlhES2dWeHVu
            amVpSkJER3BOOVY3ZUcxcFp5RnpKaEkKbDnNuq9hy5SQ46js4I8miF9c3MN2I5bq
            MUULSYqHzcAqp06wmK2cPT05/KmBriiuvsBZtnka56kwkQdq3qPSew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-02T23:29:21Z"
    mac: ENC[AES256_GCM,data:HxpIa361c33DvzEE5fzPCj9YQSRsVUrkQItqVI/itnMu307ei6KqXhMAjUC9vbKgrEku/u1XozSL7+avQ1QJrfqbobU9dPRwwI3f9+VD8L9bCwuLdh1ry3PUTXpi/uzghhzgkqc3cZx6/wjSI+D7xi3E4y/HzIWGNMgqlzSJ44o=,iv:kANQ0jQ47FZOAL6TS5BilUqMObrrTR8S1jRajg6VmpY=,tag:qnmllx2DlJ0HzIjO66teQQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
