apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:evlxWw==,iv:U8Ws29ilicFnc5UouIjiHfsR7ouAr1uNLyN/jB5zXkg=,tag:XPY5i4D+kUaCoP4LNgTQiA==,type:str]
    password: ENC[AES256_GCM,data:ahi5iXlk1tAMymaQ,iv:8LaKMQeBmhClmQlQBT13so9C2omDDT5bYZwyXZwtwfs=,tag:VFEnfJyRzOk3wO+DSRByLw==,type:str]
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: default
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:C9JDNVs2tlUMIg==,iv:cjUxD91mEKfsN2eA+s9c+eOgXY2ifBJwKYS0B/MYpOQ=,tag:8XhQjR1Mlr9XE3ZChcVlIQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:6rGXa5e0brHnNvH3pT9gY9JR/eibUdeZixMSNo+EjCM=,iv:+VBtQpOVZzX+nSMSa0A8q70XU1v9j2BYk1N4igulEdA=,tag:w4ibzbxLiUgtdaA//MaJ3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeFBVcWJQZSt2YnZSREo2
            WkZKRHI3VlZvQ2puWGQvM0VJWEszY0gzZ0hrClEvU3g3VWlNVzRJbjNlZXRuU1pD
            UE5KZ1lqdVdraWlGK3RuSjM0N25xc1kKLS0tIG9MVkRkOWRqWVg1UE5xZTBybDNV
            UFpxOUwvVmtETXI2SHdUOVNzcjZKSTgK9594Q8SmvaSWu9CAP3o50tqie8RUpJYj
            ctwihjPWpiHMDFbrPktkBotPaIebcYN2NvOBfL6pcb0EzP39QOK0xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T14:50:57Z"
    mac: ENC[AES256_GCM,data:YwUs6hAF3T/AVH2j4iJ6Imrv4qEumjoVtlwMcYH3VPyvrXYwYkMUneALQVW8Y4O2FoJdAVbrV5zNg95nz9R0S853VAhReYPS0GIS9laZ0dzZUb5MpD8BqOdI2fH8P05ESzBwXYJSDVWte4PIqxRkw2Cbv6AZ6w0DSIEA/RK+roo=,iv:XoN0cRr5abAcALSU2LwUe6w8vDXW3fKwl8zUMPaEy7A=,tag:uAV3TT8hrlTjikHV4yNicQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
