apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:BhUmtnGze8M=,iv:q90kyh+oP615KUnohzdfk6Jy2YTgGGmPHSfZeFQlpx4=,tag:QtQrDfYjvjCOaI1leFGbUg==,type:str]
    password: ENC[AES256_GCM,data:M5Y4FwhZEjCTE1PM,iv:nIrrO8Au6YA4dC4hjlHP354tzDyIlCWSiuA8uZ6QNnk=,tag:RwbcIAIA9ST2EuMkAI7Nkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaDMrcWhaV0JsY1d0Z0h6
            ZWtJR1BMbzZYLzFJckZGdkZramJBT1Y2bm5RCkVoSEIydjBjOVNFcHFhRWNYc1pC
            c29ndjRZWVlENkxwVm1ub1BoVXBuRFEKLS0tIHhhaW5Pb2loVkZtbDljMkF2YnZO
            enM1UVlCdUxyeWtPU0p0ZjdUTU4zTHcK1PlHhI89H9QGX9SI4L31u/R+f+FJ4B0L
            XQXXV1qjxuPYiqlBH0BcZJQ4Ts0aq8V4PBCLZZM0CEdQ2CgEQpPWhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T18:30:02Z"
    mac: ENC[AES256_GCM,data:oZBhEoS0tAqoXipz9mztNtgS5Doth1FNuwl8eU60cFRMsvZBYGmd9eB4QAD0r7e+kGtkyQyrtYoQOp6cVzW2VPhCcLzMY29ir05Y4yFzIBmbT6hml3+PLvwbXk0EnVsLmsEZAl+8e74sIW2R0WqQWbH0vwPrUUtynTcCN7O8YZE=,iv:E8vRjCrbX2qaQD/+go4PPK3rTTxbENJQve5CEW/wtjY=,tag:zOzCx2aM9UYeJn68iHwE3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: default
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:953Qlg6Sm1o=,iv:ERumva6/g3GIb1732VrfEdpriYTEuVuZ6sNPiGlRfug=,tag:zE6KPtMkTLI7eb1CdHVNcw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:HY8DLRGpznMaa1wdq+t1tC6iuM8Kahm9mh+oAEz4CiIyH0i8,iv:pF8u0YHie4Nsj7fWzZXkozuOVdmQe9BDOEzeEx3vKN0=,tag:HnN+NNTQbEKHVzjrlyW/tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaDMrcWhaV0JsY1d0Z0h6
            ZWtJR1BMbzZYLzFJckZGdkZramJBT1Y2bm5RCkVoSEIydjBjOVNFcHFhRWNYc1pC
            c29ndjRZWVlENkxwVm1ub1BoVXBuRFEKLS0tIHhhaW5Pb2loVkZtbDljMkF2YnZO
            enM1UVlCdUxyeWtPU0p0ZjdUTU4zTHcK1PlHhI89H9QGX9SI4L31u/R+f+FJ4B0L
            XQXXV1qjxuPYiqlBH0BcZJQ4Ts0aq8V4PBCLZZM0CEdQ2CgEQpPWhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T18:30:02Z"
    mac: ENC[AES256_GCM,data:oZBhEoS0tAqoXipz9mztNtgS5Doth1FNuwl8eU60cFRMsvZBYGmd9eB4QAD0r7e+kGtkyQyrtYoQOp6cVzW2VPhCcLzMY29ir05Y4yFzIBmbT6hml3+PLvwbXk0EnVsLmsEZAl+8e74sIW2R0WqQWbH0vwPrUUtynTcCN7O8YZE=,iv:E8vRjCrbX2qaQD/+go4PPK3rTTxbENJQve5CEW/wtjY=,tag:zOzCx2aM9UYeJn68iHwE3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
