kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: gitea-config
    namespace: default
stringData:
    password: ENC[AES256_GCM,data:vmhFbYDVlk4G1CPjKkVKZdnQRy+QfO44TFCUf/hM,iv:pNlgKwi3/IPQH6yXolZtMt72WF2MN9OxHcgGiVSBzrE=,tag:MssarUk5EYSCigccDO9SJA==,type:str]
    minio_access_key_id: ENC[AES256_GCM,data:IYFHvf2Haa9uyaHEGDbvdUKFZKQ=,iv:Wgr0tsTvYgfIhrIhhw5+IN2mpXs3AW1KWpj+p7eOwpE=,tag:l7vM3jLU6DeiN33kY7ytkg==,type:str]
    minio_secret_access_key: ENC[AES256_GCM,data:6boDRj7Hgb/aq3TmpmudMm+DGOcZBwGeNc8XcUX7GiQdA7rDQ+7oFQ==,iv:Q280707NTc9q1DTLpVU9RGZBWkMRmCIoHzyWlXcKCOE=,tag:Ihg2RyEYkCwD1gpwxMxsvg==,type:str]
    bindDn: ENC[AES256_GCM,data:pEcYkEBqSbBMNGK94yYMrb8Xc91mQA5fEAIVpE13f6azfC6lhg==,iv:7EaUNhRBSTAizXTCMTPiLaoRds5ovyQ9PZaQok90bns=,tag:e1S7Whud+HfscTkeO/WHDQ==,type:str]
    bindPassword: ENC[AES256_GCM,data:0MQBJyS8OT4WXWiLQRgeFIGnVXcPIMH2oJSM2Q==,iv:VP7sPET8w+W8ktiKs+NUKMVOm7Z/R27BVx4wlYSUQes=,tag:IHHJd8kMu22qCCP4bKNIoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkU2JyTklTL3NBUUVWem0y
            UmFwK3NxSDA2M3JubVZvbUxZMitzUXU5c2xzCmxUL2VDamRRN3g5dVJWU0wxM3Rt
            WXYwakFTQWRXc21aTkJOZ29QR2N4Y28KLS0tIGFEVnc0cngxeE9DM3pCcDVGNXl6
            WFFiV1ZPcVhURC8zb3dVTGkvNWNQN3cKur3r4+Pl79RX2GlA5Yvela+8fOyBdI16
            jmxOHT1BrO86fADa9fKma9F+2cVuWuddHP3BeqIf34bLgcT2XV62+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-02T18:24:03Z"
    mac: ENC[AES256_GCM,data:yZ0LTj6NcTdOlDnUTRAg5uEen9xiVXjXOgQFFC9nU/jJMbEComyDrGb8HCUKgn0WXEHSVAc0dyewf4xCM0GqIOJBlOLQDVECldN8KfmXAkPa9nJHHfHuLaTcFz2oSi5d2baZVJ2TPTNdEoyPxZH5xko3WyUoEV7h/PmcECPUi68=,iv:cBwYfT1aEQqIkBjKsym60qi83OYS/57UOEEsSEvmyIA=,tag:9cXra8aHxklORUnNWDS58Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
