---
# tasks file for openssh-server

- name: load OS specific variables
  include_vars: "{{ansible_facts['os_family']}}.yml"
  tags: sshd

- name: install openssh-server and openssh-client
  package: name={{sshd_packages}} state=latest
  tags: sshd

  # example output: OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013
- name: register ssh version
  command: ssh -V
  register: sshd_version
  check_mode: no
  changed_when: False

- name: template sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    backup: yes
    validate: '/usr/sbin/sshd -t -f %s'
  notify: restart_sshd
  tags: sshd

- meta: flush_handlers
