---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sumologic
  namespace: monitoring
spec:
  chart:
    spec:
      chart: sumologic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sumologic
      version: "2.14"
  interval: 1m0s
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  valuesFrom:
    - kind: ConfigMap
      name: sumologic-values
