---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-release.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: sumologic-values
    files:
      - values.yaml=my_values.yaml
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
patchesStrategicMerge:
  - patches/auth.yaml
