# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: default
type: Opaque
stringData:
    AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:68Zqx8bT2UC6YGglwmTjxlbtSPGChbtWpMu6QUj8SxueJ7YddlBN12eba9bp+3/k,iv:2ZAkb9rH/7L9lUzvYMPyPCg74AcviVAy6GWe0PekHEA=,tag:y6bII9Vis7Rl5q98yrzcvQ==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:oWnaOvq0mI5neKWVFFw2TD+Cn2aRsaz36F+bqGpsug==,iv:E20FGrnFCCBC3ZmxUMZyv6Atu230cUtYLH6LpUntTeY=,tag:avbEAj9iNP0d4Q5+XE63CQ==,type:str]
    AUTHELIA_SESSION_REDIS_PASSWORD: ENC[AES256_GCM,data:H13828w8oDkHxTbWVfYOPVBblz6b4MsyoVFZ,iv:hW4IhYBVp+PAka3NM52OfM3FuaV37qHH+sg28ZBoQaQ=,tag:+/avSN9yX84HRZecBG/qtA==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:BpPJH0wKIyt9GtTko942d/cRfp+XnizUjHi9dCqRk0PV7jo/vBDrxCPmOeM=,iv:eFPhNOlLYsexxli6wHj4bz8vm0KHznMv0UFWl+SNv8E=,tag:zFLHgDurC5DyllcHPR1M0A==,type:str]
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:uWGa3G/qr62t/AlKo3bpBM5vMQ/cthxoADM9nA==,iv:9ZfgHZf/Z2Jo188yf/a9oqHzVQihhj7Nr9NRqZow4fQ=,tag:h4t7b3pfqCn0HmKSjZioyQ==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:Uhu6HgRP6hI=,iv:VRqVowd3sEtpSHtdDst1KusgNXpEwMwX7ikQPSYiEbs=,tag:I2jp6qYf3U3VUOFzlTprxA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9Gy+gC2tQBswan4buE0D4fJYOHJ7ImhMqYJ6tI97,iv:yt7YxPlMpO2au4uJ7swlkbLklBFUrMdtDwlzOdhddAs=,tag:iNga8OEE+i0ZjyMBnjCHKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VmZqVUtNbm9rNFBlb2xJ
            RnFOTWg0cS92SzlZRXhMbVBLNW9pQ09xeFhJCkVHTW9HcnZMQk9lOSthWXVFOHky
            ZVgycUVnUXViTCtlR3haSjFlNjhvcjgKLS0tIHlSWHc0NnFhQkJTOERMVFF0b1FE
            SUtkVWtrMmlhN3pIdXFtd1NoNUxRTlUK3X838OsFjbOu9q9OD/GIzez0UqZ1pZ9v
            yr3aFUWgtblVRQ3jpGtnbCERaIt+mpN8YhzlmCtwFzGiG75exJ1fSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-30T22:24:42Z"
    mac: ENC[AES256_GCM,data:U91vlM/7diDcIGTaEQTysFWSmwr21hMx3k+0UX5diCQofPbasAFH6eN0KVXjnZH9o79w3imPndh3/IQGrLEYyDS8cD+ko11hrcR0VknOf5GQC+TymCo9TcMqRfbJgo4nfe4KGsUx/Ol0fCFrOE7YrFqtz5wop2l98rxBoF2rAuc=,iv:hkA997lcJhiJTYaZRQZoEB1lojDLLPC1AmUj+leLDwI=,tag:Fxiq8ood/Eq7yG3dGUZb7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
