# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: default
type: Opaque
stringData:
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:FqORGvh/2bY=,iv:BbycbMPI8JzaVPpN3a2eKqGcbssJqKyqO0Dp9LNfuoY=,tag:Bkt1tMlnIrLkeBMzcHkhAw==,type:str]
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:1uUXK+Rjsrbhjpko,iv:3iCL7tJi8X4OupDp2RROSdc600w2xwjYuH6zBbNJGVk=,tag:DtaD7u9TDDqww4bR/rI7TA==,type:str]
    AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:SRfKi0bo2iP9ZHqPDBolCMXAHm5uj8/zXTtIAyASNd0=,iv:2RCr/INuypNrT9N/ZMrX5x0vWR+CSNMkz/xqJwxXOzw=,tag:a1PuYosK7MjpXUalhSvvBA==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:CHyeWbMorjUt4kcHFgXwSHSEdunkWsX/LNV4/hY6sP4=,iv:fduJS7UncgVy7HGpOPQ26u4N9HJob+9Z6asRqCKRQ6k=,tag:+nLNjT4tRqmToP4mB78JpQ==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:Je+Eg+cX55NAVqEKde8ndzqGAVZY43O3+YQxR4hCYXE=,iv:pc8MFQEUAOjwi0mFI0qxBNwGNrgmb0qg+x9dppM7/+w=,tag:kd3JKbvQvX0bJCh/z8EBZg==,type:str]
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:mrfeNMA9QknTrTex,iv:xyZISdVRKysyIUv9Fqssd5S905xVbGDkT+gwbLr5SkA=,tag:WFDfOH8fkheVrSGu9kkNwA==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:pU0bD7zXCYedhP5p38UL8QMAUq3kadGi9w8aEYm1VBA=,iv:UKJi58AjVk2uQu2775OUw16pGT45yvT38NCoJbld+X8=,tag:R2zuQIdf7xMy1AgTpHxALg==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: ENC[AES256_GCM,data:v9CSt17LAIVXsAwFoiHOaBY/T4QEsNux9mMf/PBpIw8=,iv:sUSXIMFu0lMvX35n9KXMWyMEmSY6PvU/jHLph8nPIn4=,tag:3YW4/RwjJ+8bRF1If5cuqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YTZrYksvdjlHZmdSR09q
            c0Vvc0hQZG82cWhFRVZYQmJRcThCVkt5SlVvCnFCS0p0MzJ5aDJWRE1WTVp0Qndp
            a2hZUlcxUGxyU280RnpJOWFGSEtuZFkKLS0tIHV2cTdCRU53QUZoN3hSdFV0ZUJw
            WHZtc3Ntb2ZnRHpDSXB4NVlDd1BLcVUKKRynsosH/u0qyjfWy/7Xvw/Gqk6vc3mh
            dnss61uC2vpc7Wu6/5tNVQZu7TrQh65MqAZ3DVEVghcH7qxZO68YOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T14:21:22Z"
    mac: ENC[AES256_GCM,data:h9kxjFcu6d8fVMNB7sKYUE4HXVAReBo8IshKbu4U4YiytjzPauVahvlXipq+l+DH68+uCVb453iqulW2dlkcKq0DHRokP1Yo+Tga0l1eBH5b+pj5HppmIyn8vM6mrhijrAVnDwcwv0qWT82CwugxuSYIUulPAeo2GJspYTNRfGU=,iv:ofqBglRS1O21JVrh33YTR18nr2V5zBmeV/aUEW9ACc0=,tag:ZvlvkX/oExFKyt+3FQN9gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
