---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sumologic

  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: sumologic
      version: 2.14.1
      sourceRef:
        kind: HelmRepository
        name: sumologic
        namespace: flux-system
    inverval: 15m
    values:
    sumologic:
      accessId: "${SECRET_SUMO_ACCESSID)"
      accessKey: "${SECRET_SUMO_ACCESSKEY}"
      ClusterName: "${SECRET_SUMO_CLUSTER}"
  install:
    createNamespace: true
  remediation:
    retries: 5
  upgrade:
    remediation:
      retries: 5
