---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sumologic
  namespace: monitoring
spec:
  interval: 5m
  releaseName: sumo-release
  chart:
    spec:
      chart: sumologic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sumologic
      version: 2.14.1
      decryption:
        provider: sops
        secretRef:
          name: sops-gpg
  valuesFrom:
    - kind: ConfigMap
      name: sumologicMap

  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
