# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sumologic_secret_keys
    namespace: monitoring
stringData:
    accessId: ENC[AES256_GCM,data:YKQthts0soDzrK+iMM4=,iv:BE77p18uCBVLM8px989+ORIpzhxfUmkpkgVPbyln1gA=,tag:no2Vda4L8pVt5WCfBTjSdw==,type:str]
    accessKey: ENC[AES256_GCM,data:ZfT/hnpG+VtYMaethzU6WbxgaWZZfVs/fhBKSTI5pO7PtsJFP7QC5h2zhrGA/Ku5MuBC1/MrSFuou/G6z3XJgA==,iv:vDom6XR0kBnRgCBYhdGbrT+BbK7uem10b6VCGVUjZ3I=,tag:dYbsQkSjWUKV+Qabx7CfSQ==,type:str]
    ClusteName: ENC[AES256_GCM,data:Wex3hm2E/g==,iv:5t0UedAhcRdnke32XtkIPC+GGPH38foxxP2v7/1CbPg=,tag:fPeJCD58G/tIxcqlSKc4rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYVVrRnNpaVEzOGJldkM1
            L2VZNUVVWUxmNHgzd1Avc2hKZ05xbXEzaGdnCjM2Z1k5STE2eWdrM1hoWkxldW5q
            YzdIZzFzc3k0MzhHSjhMOFhZQW1ybncKLS0tIHg3VUw4M0crQ1NNUVlrbjhLYVVB
            bGpqcmlUQUxjUVA4ZGMwMEgvaSs4aTAKHRZtudyqiXmWD+o9emYZT8KRW/4QeyTf
            Xknde/YRu3uEKjjX3Kbft4nASThXOlMxuaqpW6dx58iKQ1a3C6YwEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-08T00:15:05Z"
    mac: ENC[AES256_GCM,data:Y+lE4eKNIOdeiw5AznQKk94H4TlGIg4vUFVGNCu7skhjPS8oIDaEaK2aPlEA6WOmCINRPIupVhsBtjCGGfByPYANW6fbhUTZ+r3xYI8xTg/aneerHhJ99PJORPWdoOPaD2ApbQw7WJBKUoQFFzfjzEHYJHzRMGWMBakUKi9gt6k=,iv:I3iiXDlz2736tZsH1HShIMRcMrckkw4TyFx6vSIDWl8=,tag:t/aNQfV/62VeUFsQsKLuog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
