---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: storage-team
  name: storage-team-reconciler
  namespace: csi-nfs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:csi-nfs:reconciler
- kind: ServiceAccount
  name: storage-team
  namespace: csi-nfs
