---
galaxy_info:
  author: Felix Archambault
  description: A role to install and configure openssh-server on a target host.
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 7
        - 6
    - name: Fedora
      versions:
        - 20
        - 21
        - 22
    - name: ubuntu

    - name: Ubuntu
      versions:
        - all
        - trusty
        - utopic
        - vivid
        - wily
        - xenial
        - yakkety
  galaxy_tags:
    - system
    - networking
    - openssh

dependencies: []
