# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cD0sI6iq2eVaNShAtGz537IeT2dif0tFEoT5syYUBtkbeogYs79Hig==,iv:OoX2jO8bPaj3cdkQ6jlVWXT8sO+UXPaDxUAxyH+L6e4=,tag:bJRsfMMLirM6DRGf/P3nkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOHN0UDEwNEF2ei83VUFw
            UmpDSUY1NkxzOFdrMlhNL1M0Q1NOK1IzeGkwCjVoYXEvZTl3YUlqUGQ2WVY3d05V
            T1B2U2l2Y1hlem00OEw0bHViaGI1YWcKLS0tIFYvNDdIck1PM0hWTXFNbUxzODlZ
            Qy9oQkYwZ1FTOWMwUEMzS3JJc0xieDAKSp66Ub99Q352nWpv2FELDG03lXm7jKPh
            gE7i1oL6puNCEbQOX5ZnfLozRfwxmhqRClw/HQs8eRsCiP29rRtxbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T03:56:14Z"
    mac: ENC[AES256_GCM,data:t0WdtY1eKlKur4kD2kqzPWcbOcPJoa+R6Uasn3SpbaCO1GssfEX/PbjUZQa7yv2SzmbCKJaYQZuafUmzPWL7wuM4AeDtJb0x//EIAMiVe6IRo5ifxUuvPu0HbTwWOJSCNPf0ap/ZCXX5nT78akNBqjOG/pMZX8OwC9tsKGh+LEE=,iv:Oby4rc19P8kAv3klZqJJFBoB/bo12phDoQbROxWgtkQ=,tag:ctAyPc6p+pA1baOgdpcIXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
