# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:irgaR45ehwKEQWc073G/UVOpltj4MxfBc7DxcTrsGZYFW4T7G7ilVA==,iv:5+VWUcON4CsBF8Knq//ktapXT7br4QdjBDRjUPk5Juo=,tag:8OxT3tLx/D0nvTnYBZTbaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbXJJUytMczArZlFPY2Zq
            Rkt6LytNUzJ0TG1PNVhEZFNTK3R0ZU5ZT0hjCnBRS01nVTA2cGpPc2tkSVk5Qkgw
            RjMyeUZ1TnNMWENReXl1b2d1WmtCZ0kKLS0tIDRNNy9oYTJ6Y2IxcnQ1bGUxUDN1
            UEc0VXJrTTk2cWZON0J0akkrUVJMeU0Ka0/tk/9LCos3i/rfXw0IlpBuGnljJrXy
            QIKwi1A5bEcjUimU9MBpujHOXQAe0cEUd38asRwPJCSzOXSMro3zuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-08T21:43:39Z"
    mac: ENC[AES256_GCM,data:W0HiSsP2+zAsrnKZAGzBeRLIWqBKXZQCJpGBFKrL5ujyrj9pRJ+l31HvNYAOEdWBrlWPby1C5vzkHVIHHHrTNJDmrHFZ/UvpZJ687W88VM0sKioLNVsVsfIU56CqOhyTMYTlTKVJN8ASHux//cuLeOlmT7wuF8UaWSxK6bPQ27k=,iv:YOr9EtJk+Cy8ybptsJfDS/0osHt9kmqwE5fnKeZh0K4=,tag:F0F98k0pNkkz7PXvV0ZgSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
