# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:SzkwCKoBQuu1BNb7bhpjmleufPeqj1foyk10wv727DyvBLJCZi4tWw==,iv:W6RvRBscgNUVB4Z9owaP1anKVnzv+/Bpnwir88+/1Qc=,tag:9TI/ijBUOfVVJPYLHvtiDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrS3pEdFF3aVB2Z3hWL3hq
            V0ZtOFlJYTFpR2pzVVpZUmFEWXp5NnVMRFNrCjRrUHI0bTdWRXAveGlrRzhrTVRC
            cmtYamo5UzQrMjgrMkU0WHJNcXZudW8KLS0tIFN5ZFpPUnIrRGFndDUyNUxMSnBR
            Q2hIbSsxbkdFOVg5WUVqUWhnc1RmSU0KLNIcVs0bEZHypeO3BwduwEPMFz61pgjK
            BKjTEQf+j9ImB3S8wbtbPY326nbVaWAFrdnGo8Cls3xmLHYZa8oueg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-02T23:29:21Z"
    mac: ENC[AES256_GCM,data:ORNkjykpjtKRcMRYeaulKxqf6LCoF3Jk58L+oItS6zUIGhXNMFSIVdPw/JUFmpF9wSJe6Dk+1TqZY8uW93KZ0sP3+/jLB5ZvwSqIjGf8yvBvV6eWuSyJ4PUFe95au9UuEjvywRQgQMmvUYCWQSk5V8t/lDQ96NkG6RjlhRK3fLo=,iv:/O0iee16VOeMJKG/KvWLRgJwsc4C88wQD16Jo5CLXIg=,tag:RoCW0e0IPIv1FLwSXQZIMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
