# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7tbOBy/XRpw=,iv:wf026cQIwc+9yVjvw+grOxeQHnS6DawJN4VraWNUUL4=,tag:MbQ4A955ochrFt1mwRB/mA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBna1B3ZW41WWlsYXVVakxE
            aDVoMDA2QTBHMit3K1RycGpURGdJSy9SRkFrCkM2UTFLREE5TWhZMmVJNVdmS0c3
            YWx3WWY4S2RkWEJRT0VkejF4K2ppNUEKLS0tIG4wTG9ObzM3NXN1NUdyWDdDdXpk
            MlNCQ1M5YkcrSE96WGNXS0ZzR3ZGUGcK7F3uFhoMf/EtIP7FiCDOZimEzQxt8WzN
            pyXn8CigKJq3pd30EB0j/+w5Xyj0LebEDe3xaKDhhzliTbc3WZ21ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-06T01:06:08Z"
    mac: ENC[AES256_GCM,data:25gGbDe/UapjgcWtFLhMMkIH5QzPDyNidi22bxnLuEknKjmfYUQJFA4NNiwUlBs5x4KuslW6B6NH+3vsTA9drNB7fV60hka75ZOHb6wgOcN/0+ZmmJEExsxy6Wl56iuSP/CGtiAsGXKEO30cff7EIKyMjpr1oGs6F8ZjozBL22Y=,iv:WMw8O0GNAt3geXurO0rg4+RTfk2ZvW5835I/TKdTk/Q=,tag:xyPTHBwwlEPIK1tEOWJn+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
