---
kubernetes:
  children:
    master:
      hosts:
        hassio.media:
          ansible_host: 172.16.30.201
    worker:
      hosts:
        server1.lab:
          ansible_host: 172.16.70.10
          rook_devices:
            - /dev/mapper/fedora_fedora-ceph
        server2.lab:
          ansible_host: 172.16.70.20
          rook_devices:
            - /dev/mapper/fedora_fedora-ceph
        server3.lab:
          ansible_host: 172.16.70.30
          rook_devices:
            - /dev/mapper/fedora_fedora-ceph
