---
kubernetes:
  children:
    master:
      hosts:
        hassio.media:
          ansible_host: 172.16.30.201
      vars:
        ansible_user: cfallwell
        ansible_ssh_port: 22
    worker:
      hosts:
        server1.lab:
          ansible_host: 172.16.70.10
          rook_devices:
            - /dev/mapper/fedora_fedora-ceph
        server2.lab:
          ansible_host: 172.16.70.20
          rook_devices:
            - /dev/mapper/fedora_fedora-ceph
        server3.lab:
          ansible_host: 172.16.70.30
          rook_devices:
            - /dev/mapper/fedora_fedora-ceph
      vars:
        ansible_user: cfallwell
