---
timezone: America/Chicago

public_ssh_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOdorMN2jRq08LisRe1qubhOCa9/LdweToE8U0cMu1E13uuRswgGWmFVP1jgIm5AhsgvK6+9tryb2Hja1gWmo/2IvuqZrM2HHbJxv9rJjzDfMZj4aiRv8BwNLuwFnTMbzBF4/ak++0okXYhYGZX9D3py8uoRF9hxP4Etn2HIWIBtB49sq53ltbnZD9LqUUEIW1VWWt1B/NxoxHfGHyncmZGBlQg1spu1Ikk8DedYjn0XdT5L5Ms+yr+I4BDSJhGHPBifLYiMzMR5vqryPNpf3LbrHSZgc4L+diuFs3iDjoQ6YnRbxeTwafg268I38RV8SpLBt+uNzYVJTGjUezA6rh colinfallwell@iMac-Pro.attlocal.net"

# TODO(ansible): Some packages might be required for newer Intel CPU generations
# https://ask.fedoraproject.org/t/intel-graphics-best-practices-and-settings-for-hardware-acceleration/21119
packages:
  - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  - dnf-automatic
  - dnf-utils
  - fish
  - hdparm
  - htop
  - intel-gpu-tools
  - ipvsadm
  - kernel-devel       # required by falco
  - kernel-headers     # required by falco
  - lm_sensors
  - nano
  - nvme-cli
  - socat
