# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr
    namespace: default
type: Opaque
stringData:
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:fQtJm8ecG4yZaDl+DXAKMQi4x+N28qMZ2jEYlh2a,iv:jqOTgcswXmJDzbOe+QW5uLv9e7pmiZDeCSQzfB3U79o=,tag:xh34nLq9fS9LT9W6thCK9Q==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:Z4eMdtv7BoKMpaJzvqqs9ETK4EPcm/BZNXXvmbMM,iv:rwI9P9mb1FqNPzEuMORdMFdR3xA9dvIEcA6bXFFu3EQ=,tag:1dVt8Q0T9wZ7b/NXQoPU8A==,type:str]
    RADARR__API_KEY: ENC[AES256_GCM,data:UrN+518Zy8qyyPaS72Y9Sdc0hDW3YoiiFcKSMPpRKvntyvIN5vMItqUNTJB0vjvQc0v8hVOqnQTb8VCXY+sKpEheExrJkAno7Dkc5nvtpOBZn3eEfRc/D/qtOuKpQ0//ieXJbY7XTkIMF3HHyIhKQ7EU0rRBXQafIXJJZN9vVZ4=,iv:rjQyNiFMSgJPYOmcz0dX5rKMWmaS6FsNqnKzFtuQins=,tag:ijhud44TmOb37bABNx1gDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUnI5aEg2bjdFZ3ova2xN
            KzBwM2JZczY3bGxOdFJTSkNpNHRlN09MTVQ4CjhyR1B1dlVIUUlZOWtzcHBPZHZx
            bmFOcUNtZGhzSUNLSG5KM0plRDhTUjQKLS0tIGRyU2ZxcHc0MDI4aTRxZS9POXhh
            M3lVdHowY3lnNXJ0NEVwNytTWkV6YmsKKya9NWOVgjTMV6R2+MMMdyjhHYD84iQB
            g9kdGV7iqnNyZAaqhB7CoXFBmGwG8ytjxzePRRFcYJUl0ScOD5+cTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T18:58:42Z"
    mac: ENC[AES256_GCM,data:K6rgpdl5+PAPXjPUUTAPZXaXnMUaChvBx1lXyeliMf/jmFD9nDn57erAT+YzlJyac+VwplVGYSZLdNtupMaJDSNcdwM0whCW4keZCY44dGFifD+8DZbPFAm5Sa1bEmK1RjTld4DeaQaBJAkNAXFgzhS+KdjwfeNiFHy3FeEb6BE=,iv:haGDJADsT6CpCa+Lu+T9wPJUaKPC/CjPlgu3djehiaA=,tag:QIX/cUGC0lyJMpkM/U//eA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
